/*
 Copyright (c) 2014-2017, Alessandro Gatti - frob.it
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#import "FRBGeneric65816.h"
#import "FRBBase.h"

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedClassInspection"

static const struct FRBOpcode kOpcodeTable[256];

@implementation ItFrobHopper65816Generic65816

+ (NSString *_Nonnull)family {
  return @"Generic";
}

+ (NSString *_Nonnull)model {
  return @"65816";
}

+ (BOOL)exported {
  return YES;
}

+ (int)addressSpaceWidth {
  return 24;
}

- (const struct FRBOpcode *)opcodeForByte:(uint8_t)byte {
  return &kOpcodeTable[byte];
}

@end

static const struct FRBOpcode kOpcodeTable[256] = {
    {OpcodeBRK, ModeStack, N, S | P},
    {OpcodeORA, ModeDirectIndexedIndirect, A | D | X, A},
    {OpcodeCOP, ModeImmediate, S, S},
    {OpcodeORA, ModeStackRelative, A | D | S, A},
    {OpcodeTSB, ModeDirect, A | D, N},
    {OpcodeORA, ModeDirect, A | D, A},
    {OpcodeASL, ModeDirect, D, N},
    {OpcodeORA, ModeDirectIndirectLong, A | D, A},
    {OpcodePHP, ModeStack, P | S, S},
    {OpcodeORA, ModeImmediate, A, A},
    {OpcodeASL, ModeAccumulator, A, A},
    {OpcodePHD, ModeStack, D | S, S},
    {OpcodeTSB, ModeAbsolute, A, N},
    {OpcodeORA, ModeAbsolute, A, A},
    {OpcodeASL, ModeAbsolute, N, N},
    {OpcodeORA, ModeAbsoluteLong, A, A},
    {OpcodeBPL, ModeProgramCounterRelative, N, N},
    {OpcodeORA, ModeDirectIndirectIndexedY, A | D, A},
    {OpcodeORA, ModeDirectIndirect, A | D, A},
    {OpcodeORA, ModeStackRelativeIndirectIndexed, A | D | Y | S, A},
    {OpcodeTRB, ModeDirect, A | D, N},
    {OpcodeORA, ModeDirectIndexedX, A | D | X, A},
    {OpcodeASL, ModeDirectIndexedX, D | X, N},
    {OpcodeORA, ModeDirectIndirectLongIndexed, A | Y, A},
    {OpcodeCLC, ModeImplied, N, N},
    {OpcodeORA, ModeAbsoluteIndexedY, A | Y, A},
    {OpcodeINC, ModeAccumulator, A, A},
    {OpcodeTCS, ModeImplied, C, S},
    {OpcodeTRB, ModeAbsolute, A, N},
    {OpcodeORA, ModeAbsoluteIndexedX, A | X, A},
    {OpcodeASL, ModeAbsoluteIndexedX, A | X, N},
    {OpcodeORA, ModeAbsoluteLongIndexed, A, A},
    {OpcodeJSR, ModeAbsolute, N, N},
    {OpcodeAND, ModeDirectIndexedIndirect, A | D | X, A},
    {OpcodeJSL, ModeAbsoluteLong, N, N},
    {OpcodeAND, ModeStackRelativeIndirectIndexed, A | D | Y | S, A},
    {OpcodeBIT, ModeDirect, A | D, P},
    {OpcodeAND, ModeDirect, A | D, A},
    {OpcodeROL, ModeDirect, N, N},
    {OpcodeAND, ModeDirectIndirectLong, A, A},
    {OpcodePLP, ModeStack, S, P | S},
    {OpcodeAND, ModeImmediate, A, A},
    {OpcodeROL, ModeAccumulator, A, A},
    {OpcodePLD, ModeStack, S, D | S},
    {OpcodeBIT, ModeAbsolute, A, P},
    {OpcodeAND, ModeAbsolute, A, A},
    {OpcodeROL, ModeAbsolute, N, N},
    {OpcodeAND, ModeAbsoluteLong, A, A},
    {OpcodeBMI, ModeProgramCounterRelative, N, N},
    {OpcodeAND, ModeDirectIndirectIndexedY, A | D | Y, A},
    {OpcodeAND, ModeDirectIndirect, A | D, A},
    {OpcodeAND, ModeStackRelativeIndirectIndexed, A | D | S | Y, A},
    {OpcodeBIT, ModeDirectIndexedX, A | D | X, P},
    {OpcodeAND, ModeDirectIndexedX, A | D | X, A},
    {OpcodeROL, ModeDirectIndexedX, D | X, N},
    {OpcodeAND, ModeDirectIndirectLongIndexed, A | D | Y, A},
    {OpcodeSEC, ModeImplied, N, P},
    {OpcodeAND, ModeAbsoluteIndexedY, A | Y, A},
    {OpcodeDEC, ModeAccumulator, A, A},
    {OpcodeTSC, ModeImplied, S, C},
    {OpcodeBIT, ModeAbsoluteIndexedX, A | X, P},
    {OpcodeAND, ModeAbsoluteIndexedX, A | X, A},
    {OpcodeROL, ModeAbsoluteIndexedX, A | X, N},
    {OpcodeAND, ModeAbsoluteLongIndexed, A | X, A},
    {OpcodeRTI, ModeStack, N, N},
    {OpcodeEOR, ModeDirectIndexedX, A | D | X, A},
    {OpcodeWDM, ModeImplied, N, N},
    {OpcodeEOR, ModeStackRelative, A | D | S, A},
    {OpcodeMVP, ModeBlockMove, C | X | Y, C | X | Y},
    {OpcodeEOR, ModeDirect, A | D, A},
    {OpcodeLSR, ModeDirect, D, N},
    {OpcodeEOR, ModeDirectIndirectLong, A | D, A},
    {OpcodePHA, ModeStack, A | S, S},
    {OpcodeEOR, ModeImmediate, A, A},
    {OpcodeLSR, ModeAccumulator, A, A},
    {OpcodePHK, ModeStack, PBR | S, S},
    {OpcodeJMP, ModeAbsolute, N, N},
    {OpcodeEOR, ModeAbsolute, A, A},
    {OpcodeLSR, ModeAbsolute, N, N},
    {OpcodeEOR, ModeAbsoluteLong, A, A},
    {OpcodeBVC, ModeProgramCounterRelative, N, N},
    {OpcodeEOR, ModeDirectIndirectIndexedY, A | D | Y, A},
    {OpcodeEOR, ModeDirectIndirect, A | D, A},
    {OpcodeEOR, ModeStackRelativeIndirectIndexed, A | D | S | Y, A},
    {OpcodeMVN, ModeBlockMove, C | X | Y, C | X | Y},
    {OpcodeEOR, ModeDirectIndexedX, A | D | X, A},
    {OpcodeLSR, ModeDirectIndexedX, X | D, N},
    {OpcodeEOR, ModeDirectIndirectLongIndexed, A | D | Y, A},
    {OpcodeCLI, ModeImplied, N, N},
    {OpcodeEOR, ModeAbsoluteIndexedY, A | Y, A},
    {OpcodePHY, ModeStack, Y | S, S},
    {OpcodeTCD, ModeImplied, A, D},
    {OpcodeJML, ModeAbsoluteLong, N, N},
    {OpcodeEOR, ModeAbsoluteIndexedX, A | X, A},
    {OpcodeLSR, ModeAbsoluteIndexedX, A | X, N},
    {OpcodeEOR, ModeAbsoluteLongIndexed, A | X, A},
    {OpcodeRTS, ModeStack, N, N},
    {OpcodeADC, ModeDirectIndexedIndirect, N, N},
    {OpcodePER, ModeProgramCounterRelativeLong, S, S},
    {OpcodeADC, ModeStackRelative, A | D | S, A},
    {OpcodeSTZ, ModeDirect, N, N},
    {OpcodeADC, ModeDirect, A | D, A},
    {OpcodeROR, ModeDirect, N, N},
    {OpcodeADC, ModeDirectIndirectLong, A | D, A},
    {OpcodePLA, ModeStack, S, A | S},
    {OpcodeADC, ModeImmediate, A, A},
    {OpcodeROR, ModeAccumulator, A, A},
    {OpcodeRTL, ModeStack, N, N},
    {OpcodeJMP, ModeAbsoluteIndirect, N, N},
    {OpcodeADC, ModeAbsolute, A, A},
    {OpcodeROR, ModeAbsolute, N, N},
    {OpcodeADC, ModeAbsoluteLong, A, A},
    {OpcodeBVS, ModeProgramCounterRelative, N, N},
    {OpcodeADC, ModeDirectIndirectIndexedY, A | D | Y, A},
    {OpcodeADC, ModeDirectIndirect, A | D, A},
    {OpcodeADC, ModeStackRelativeIndirectIndexed, A | D | Y | S, A},
    {OpcodeSTZ, ModeDirectIndexedX, A | D | X, N},
    {OpcodeADC, ModeDirectIndexedX, A | D | X, A},
    {OpcodeROR, ModeDirectIndexedX, A | D | X, N},
    {OpcodeADC, ModeDirectIndirectLongIndexed, A | D | Y, A},
    {OpcodeSEI, ModeImplied, N, N},
    {OpcodeADC, ModeAbsoluteIndexedY, A | Y, A},
    {OpcodePLY, ModeStack, S, Y | S},
    {OpcodeTDC, ModeImplied, C | D, C | D},
    {OpcodeJMP, ModeAbsoluteIndexedIndirect, X, N},
    {OpcodeADC, ModeAbsoluteIndexedX, A | X, A},
    {OpcodeROR, ModeAbsoluteIndexedX, X, N},
    {OpcodeADC, ModeAbsoluteLongIndexed, A | X, A},
    {OpcodeBRA, ModeProgramCounterRelative, N, N},
    {OpcodeSTA, ModeDirectIndexedIndirect, A | D | X, N},
    {OpcodeBRL, ModeProgramCounterRelativeLong, N, N},
    {OpcodeSTA, ModeStackRelative, A | D | S, N},
    {OpcodeSTY, ModeDirect, Y | D, N},
    {OpcodeSTA, ModeDirect, A | D, N},
    {OpcodeSTX, ModeDirect, X | D, N},
    {OpcodeSTA, ModeDirectIndirectLong, A | D, N},
    {OpcodeDEY, ModeImplied, Y, Y},
    {OpcodeBIT, ModeImmediate, A, N},
    {OpcodeTXA, ModeImplied, A | X, A | X},
    {OpcodePHB, ModeStack, D | S, S},
    {OpcodeSTY, ModeAbsolute, Y, N},
    {OpcodeSTA, ModeAbsolute, A, N},
    {OpcodeSTX, ModeAbsolute, X, N},
    {OpcodeSTA, ModeAbsoluteLong, A, N},
    {OpcodeBCC, ModeProgramCounterRelative, N, N},
    {OpcodeSTA, ModeDirectIndirectIndexedY, A | D | Y, N},
    {OpcodeSTA, ModeDirectIndirect, A | D, N},
    {OpcodeSTA, ModeStackRelativeIndirectIndexed, A | D | Y | S, N},
    {OpcodeSTY, ModeDirectIndexedX, D | X | Y, N},
    {OpcodeSTA, ModeDirectIndexedX, A | D | X, N},
    {OpcodeSTX, ModeDirectIndexedY, D | X | Y, N},
    {OpcodeSTA, ModeDirectIndirectLongIndexed, A | D | Y, N},
    {OpcodeTYA, ModeImplied, A | Y, A | Y},
    {OpcodeSTA, ModeAbsoluteIndexedY, A | Y, N},
    {OpcodeTXS, ModeImplied, X | S, X | S},
    {OpcodeTXY, ModeImplied, X | Y, X | Y},
    {OpcodeSTZ, ModeAbsolute, N, N},
    {OpcodeSTA, ModeAbsoluteIndexedX, A | X, N},
    {OpcodeSTZ, ModeAbsoluteIndexedX, X, N},
    {OpcodeSTA, ModeAbsoluteLongIndexed, A | X, N},
    {OpcodeLDY, ModeImmediate, N, Y},
    {OpcodeLDA, ModeDirectIndexedX, D | X, A},
    {OpcodeLDX, ModeImmediate, N, X},
    {OpcodeLDA, ModeStackRelative, D | S, A},
    {OpcodeLDY, ModeDirect, D, Y},
    {OpcodeLDA, ModeDirect, D, A},
    {OpcodeLDX, ModeDirect, D, X},
    {OpcodeLDA, ModeDirectIndirectLong, D, A},
    {OpcodeTAY, ModeImplied, A | Y, A | Y},
    {OpcodeLDA, ModeImmediate, N, A},
    {OpcodeTAX, ModeImplied, A | X, A | X},
    {OpcodePLB, ModeStack, S, D | S},
    {OpcodeLDY, ModeAbsolute, N, Y},
    {OpcodeLDA, ModeAbsolute, N, A},
    {OpcodeLDX, ModeAbsolute, N, X},
    {OpcodeLDA, ModeAbsoluteLong, N, A},
    {OpcodeBCS, ModeProgramCounterRelative, N, N},
    {OpcodeLDA, ModeDirectIndirectIndexedY, D | Y, A},
    {OpcodeLDA, ModeDirectIndirect, D, A},
    {OpcodeLDY, ModeStackRelativeIndirectIndexed, D | Y | S, Y},
    {OpcodeLDY, ModeDirectIndexedX, D | X, Y},
    {OpcodeLDA, ModeDirectIndexedX, D | X, A},
    {OpcodeLDX, ModeDirectIndexedY, D | Y, X},
    {OpcodeLDA, ModeDirectIndirectLongIndexed, D | Y, A},
    {OpcodeCLV, ModeImplied, N, N},
    {OpcodeLDA, ModeAbsoluteIndexedY, Y, A},
    {OpcodeTSX, ModeImplied, X | S, X | S},
    {OpcodeTYX, ModeImplied, X | Y, X | Y},
    {OpcodeLDY, ModeAbsoluteIndexedX, X, Y},
    {OpcodeLDA, ModeAbsoluteIndexedX, X, A},
    {OpcodeLDX, ModeAbsoluteIndexedY, Y, X},
    {OpcodeLDA, ModeAbsoluteLongIndexed, X, A},
    {OpcodeCPY, ModeImmediate, Y, N},
    {OpcodeCMP, ModeDirectIndexedIndirect, A | D | X, N},
    {OpcodeREP, ModeImmediate, N, N},
    {OpcodeCMP, ModeStackRelative, A | D | S, N},
    {OpcodeCPY, ModeDirect, D | Y, N},
    {OpcodeCMP, ModeDirect, A | D, N},
    {OpcodeDEC, ModeDirect, D, N},
    {OpcodeCMP, ModeDirectIndirectLong, A | D, N},
    {OpcodeINY, ModeImplied, Y, Y},
    {OpcodeCMP, ModeImmediate, A, N},
    {OpcodeDEX, ModeImplied, X, X},
    {OpcodeWAI, ModeImplied, N, N},
    {OpcodeCPY, ModeAbsolute, Y, N},
    {OpcodeCMP, ModeAbsolute, A, N},
    {OpcodeDEC, ModeAbsolute, A, A},
    {OpcodeCMP, ModeAbsoluteLong, A, N},
    {OpcodeBNE, ModeProgramCounterRelative, N, N},
    {OpcodeCMP, ModeDirectIndirectIndexedY, A | D | Y, N},
    {OpcodeCMP, ModeDirectIndirect, A | D, N},
    {OpcodeCMP, ModeStackRelativeIndirectIndexed, A | D | Y | S, N},
    {OpcodePEI, ModeDirectIndirect, S, S},
    {OpcodeCMP, ModeDirectIndexedX, A | D | X, N},
    {OpcodeDEC, ModeDirectIndexedX, D | X, N},
    {OpcodeCMP, ModeDirectIndirectLongIndexed, A | D | Y, N},
    {OpcodeCLD, ModeImplied, N, N},
    {OpcodeCMP, ModeAbsoluteIndexedY, A | Y, N},
    {OpcodePHX, ModeStack, X, X | S},
    {OpcodeSTP, ModeImplied, N, N},
    {OpcodeJML, ModeAbsoluteIndirect, N, N},
    {OpcodeCMP, ModeAbsoluteIndexedX, A | X, N},
    {OpcodeDEC, ModeAbsoluteIndexedX, X, N},
    {OpcodeCMP, ModeAbsoluteLongIndexed, A | X, N},
    {OpcodeCPX, ModeImmediate, X, N},
    {OpcodeSBC, ModeDirectIndexedIndirect, A | D | X, A},
    {OpcodeSEP, ModeImmediate, N, N},
    {OpcodeSBC, ModeStackRelative, A | D | S, A},
    {OpcodeCPX, ModeDirect, X | D, N},
    {OpcodeSBC, ModeDirect, A | D, A},
    {OpcodeINC, ModeDirect, D, N},
    {OpcodeSBC, ModeDirectIndirectLong, A | D, A},
    {OpcodeINX, ModeImplied, X, X},
    {OpcodeSBC, ModeImmediate, A, A},
    {OpcodeNOP, ModeImplied, N, N},
    {OpcodeXBA, ModeImplied, A | B, A | B},
    {OpcodeCPX, ModeAbsolute, X, N},
    {OpcodeSBC, ModeAbsolute, A, A},
    {OpcodeINC, ModeAbsolute, N, N},
    {OpcodeSBC, ModeAbsoluteLong, A, A},
    {OpcodeBEQ, ModeProgramCounterRelative, N, N},
    {OpcodeSBC, ModeDirectIndirectIndexedY, A | D | Y, A},
    {OpcodeSBC, ModeDirectIndirect, A | D, A},
    {OpcodeSBC, ModeStackRelativeIndirectIndexed, A | D | Y | S, A},
    {OpcodePEA, ModeAbsolute, S, S},
    {OpcodeSBC, ModeDirectIndexedX, A | D | X, A},
    {OpcodeINC, ModeDirectIndexedX, D | X, N},
    {OpcodeSBC, ModeDirectIndirectLongIndexed, A | D | Y, A},
    {OpcodeSED, ModeImplied, N, N},
    {OpcodeSBC, ModeAbsoluteIndexedY, A | Y, A},
    {OpcodePLX, ModeStack, S, X | S},
    {OpcodeXCE, ModeImplied, P, P},
    {OpcodeJSR, ModeAbsoluteIndexedIndirect, X | S, S},
    {OpcodeSBC, ModeAbsoluteIndexedX, A | X, A},
    {OpcodeINC, ModeAbsoluteIndexedX, X, N},
    {OpcodeSBC, ModeAbsoluteLongIndexed, A | X, A}};

#pragma clang diagnostic pop
