/*
 Copyright (c) 2014, Alessandro Gatti - frob.it
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef FRBGeneric65C02Table_h
#define FRBGeneric65C02Table_h

#import "FRBBase.h"

static const struct FRBOpcode FRBGeneric65C02OpcodeTable[256] = {
    /* $00 */ { FRBOpcodeTypeBRK, FRBAddressModeImplied },
    /* $01 */ { FRBOpcodeTypeORA, FRBAddressModeIndirectXIndexed },
    /* $02 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $03 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $04 */ { FRBOpcodeTypeTSB, FRBAddressModeZeropage },
    /* $05 */ { FRBOpcodeTypeORA, FRBAddressModeZeropage },
    /* $06 */ { FRBOpcodeTypeASL, FRBAddressModeZeropage },
    /* $07 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $08 */ { FRBOpcodeTypePHP, FRBAddressModeImplied },
    /* $09 */ { FRBOpcodeTypeORA, FRBAddressModeImmediate },
    /* $0A */ { FRBOpcodeTypeASL, FRBAddressModeImplied },
    /* $0B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $0C */ { FRBOpcodeTypeTSB, FRBAddressModeAbsolute },
    /* $0D */ { FRBOpcodeTypeORA, FRBAddressModeAbsolute },
    /* $0E */ { FRBOpcodeTypeASL, FRBAddressModeAbsolute },
    /* $0F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $10 */ { FRBOpcodeTypeBPL, FRBAddressModeRelative },
    /* $11 */ { FRBOpcodeTypeORA, FRBAddressModeIndirectYIndexed },
    /* $12 */ { FRBOpcodeTypeORA, FRBAddressModeZeropageIndirect },
    /* $13 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $14 */ { FRBOpcodeTypeTRB, FRBAddressModeZeropage },
    /* $15 */ { FRBOpcodeTypeORA, FRBAddressModeZeropageXIndexed },
    /* $16 */ { FRBOpcodeTypeASL, FRBAddressModeZeropageXIndexed },
    /* $17 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $18 */ { FRBOpcodeTypeCLC, FRBAddressModeImplied },
    /* $19 */ { FRBOpcodeTypeORA, FRBAddressModeAbsoluteYIndexed },
    /* $1A */ { FRBOpcodeTypeINC, FRBAddressModeImplied },
    /* $1B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $1C */ { FRBOpcodeTypeTRB, FRBAddressModeAbsolute },
    /* $1D */ { FRBOpcodeTypeORA, FRBAddressModeAbsoluteXIndexed },
    /* $1E */ { FRBOpcodeTypeASL, FRBAddressModeAbsoluteXIndexed },
    /* $1F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $20 */ { FRBOpcodeTypeJSR, FRBAddressModeAbsolute },
    /* $21 */ { FRBOpcodeTypeAND, FRBAddressModeIndirectXIndexed },
    /* $22 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $23 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $24 */ { FRBOpcodeTypeBIT, FRBAddressModeZeropage },
    /* $25 */ { FRBOpcodeTypeAND, FRBAddressModeZeropage },
    /* $26 */ { FRBOpcodeTypeROL, FRBAddressModeZeropage },
    /* $27 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $28 */ { FRBOpcodeTypePLP, FRBAddressModeImplied },
    /* $29 */ { FRBOpcodeTypeAND, FRBAddressModeImmediate },
    /* $2A */ { FRBOpcodeTypeROL, FRBAddressModeImplied },
    /* $2B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $2C */ { FRBOpcodeTypeBIT, FRBAddressModeAbsolute },
    /* $2D */ { FRBOpcodeTypeAND, FRBAddressModeAbsolute },
    /* $2E */ { FRBOpcodeTypeROL, FRBAddressModeAbsolute },
    /* $2F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $30 */ { FRBOpcodeTypeBMI, FRBAddressModeRelative },
    /* $31 */ { FRBOpcodeTypeAND, FRBAddressModeIndirectYIndexed },
    /* $32 */ { FRBOpcodeTypeAND, FRBAddressModeZeropageIndirect },
    /* $33 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $34 */ { FRBOpcodeTypeBIT, FRBAddressModeZeropageXIndexed },
    /* $35 */ { FRBOpcodeTypeAND, FRBAddressModeZeropageXIndexed },
    /* $36 */ { FRBOpcodeTypeROL, FRBAddressModeZeropageXIndexed },
    /* $37 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $38 */ { FRBOpcodeTypeSEC, FRBAddressModeImplied },
    /* $39 */ { FRBOpcodeTypeAND, FRBAddressModeAbsoluteYIndexed },
    /* $3A */ { FRBOpcodeTypeDEC, FRBAddressModeImplied },
    /* $3B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $3C */ { FRBOpcodeTypeBIT, FRBAddressModeAbsoluteXIndexed },
    /* $3D */ { FRBOpcodeTypeAND, FRBAddressModeAbsoluteXIndexed },
    /* $3E */ { FRBOpcodeTypeROL, FRBAddressModeAbsoluteXIndexed },
    /* $3F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $40 */ { FRBOpcodeTypeRTI, FRBAddressModeImplied },
    /* $41 */ { FRBOpcodeTypeEOR, FRBAddressModeIndirectXIndexed },
    /* $42 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $43 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $44 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $45 */ { FRBOpcodeTypeEOR, FRBAddressModeZeropage },
    /* $46 */ { FRBOpcodeTypeLSR, FRBAddressModeZeropage },
    /* $47 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $48 */ { FRBOpcodeTypePHA, FRBAddressModeImplied },
    /* $49 */ { FRBOpcodeTypeEOR, FRBAddressModeImmediate },
    /* $4A */ { FRBOpcodeTypeLSR, FRBAddressModeImplied },
    /* $4B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $4C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsolute },
    /* $4D */ { FRBOpcodeTypeEOR, FRBAddressModeAbsolute },
    /* $4E */ { FRBOpcodeTypeLSR, FRBAddressModeAbsolute },
    /* $4F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $50 */ { FRBOpcodeTypeBVC, FRBAddressModeRelative },
    /* $51 */ { FRBOpcodeTypeEOR, FRBAddressModeIndirectYIndexed },
    /* $52 */ { FRBOpcodeTypeEOR, FRBAddressModeZeropageIndirect },
    /* $53 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $54 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $55 */ { FRBOpcodeTypeEOR, FRBAddressModeZeropageXIndexed },
    /* $56 */ { FRBOpcodeTypeLSR, FRBAddressModeZeropageXIndexed },
    /* $57 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $58 */ { FRBOpcodeTypeCLI, FRBAddressModeImplied },
    /* $59 */ { FRBOpcodeTypeEOR, FRBAddressModeAbsoluteYIndexed },
    /* $5A */ { FRBOpcodeTypePHY, FRBAddressModeImplied },
    /* $5B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $5C */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $5D */ { FRBOpcodeTypeEOR, FRBAddressModeAbsoluteXIndexed },
    /* $5E */ { FRBOpcodeTypeLSR, FRBAddressModeAbsoluteXIndexed },
    /* $5F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $60 */ { FRBOpcodeTypeRTS, FRBAddressModeImplied },
    /* $61 */ { FRBOpcodeTypeADC, FRBAddressModeIndirectXIndexed },
    /* $62 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $63 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $64 */ { FRBOpcodeTypeSTZ, FRBAddressModeZeropage },
    /* $65 */ { FRBOpcodeTypeADC, FRBAddressModeZeropage },
    /* $66 */ { FRBOpcodeTypeROR, FRBAddressModeZeropage },
    /* $67 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $68 */ { FRBOpcodeTypePLA, FRBAddressModeImplied },
    /* $69 */ { FRBOpcodeTypeADC, FRBAddressModeImmediate },
    /* $6A */ { FRBOpcodeTypeROR, FRBAddressModeImplied },
    /* $6B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $6C */ { FRBOpcodeTypeJMP, FRBAddressModeIndirect },
    /* $6D */ { FRBOpcodeTypeADC, FRBAddressModeAbsolute },
    /* $6E */ { FRBOpcodeTypeROR, FRBAddressModeAbsolute },
    /* $6F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $70 */ { FRBOpcodeTypeBVS, FRBAddressModeRelative },
    /* $71 */ { FRBOpcodeTypeADC, FRBAddressModeIndirectYIndexed },
    /* $72 */ { FRBOpcodeTypeADC, FRBAddressModeZeropageIndirect },
    /* $73 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $74 */ { FRBOpcodeTypeSTZ, FRBAddressModeZeropageXIndexed },
    /* $75 */ { FRBOpcodeTypeADC, FRBAddressModeZeropageXIndexed },
    /* $76 */ { FRBOpcodeTypeROR, FRBAddressModeZeropageXIndexed },
    /* $77 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $78 */ { FRBOpcodeTypeSEI, FRBAddressModeImplied },
    /* $79 */ { FRBOpcodeTypeADC, FRBAddressModeAbsoluteYIndexed },
    /* $7A */ { FRBOpcodeTypePLY, FRBAddressModeImplied },
    /* $7B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $7C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsoluteXIndexed },
    /* $7D */ { FRBOpcodeTypeADC, FRBAddressModeAbsoluteXIndexed },
    /* $7E */ { FRBOpcodeTypeROR, FRBAddressModeAbsoluteXIndexed },
    /* $7F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $80 */ { FRBOpcodeTypeBRA, FRBAddressModeRelative },
    /* $81 */ { FRBOpcodeTypeSTA, FRBAddressModeIndirectXIndexed },
    /* $82 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $83 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $84 */ { FRBOpcodeTypeSTY, FRBAddressModeZeropage },
    /* $85 */ { FRBOpcodeTypeSTA, FRBAddressModeZeropage },
    /* $86 */ { FRBOpcodeTypeSTX, FRBAddressModeZeropage },
    /* $87 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $88 */ { FRBOpcodeTypeDEY, FRBAddressModeImplied },
    /* $89 */ { FRBOpcodeTypeBIT, FRBAddressModeImmediate },
    /* $8A */ { FRBOpcodeTypeTXA, FRBAddressModeImplied },
    /* $8B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $8C */ { FRBOpcodeTypeSTY, FRBAddressModeAbsolute },
    /* $8D */ { FRBOpcodeTypeSTA, FRBAddressModeAbsolute },
    /* $8E */ { FRBOpcodeTypeSTX, FRBAddressModeAbsolute },
    /* $8F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $90 */ { FRBOpcodeTypeBCC, FRBAddressModeRelative },
    /* $91 */ { FRBOpcodeTypeSTA, FRBAddressModeIndirectYIndexed },
    /* $92 */ { FRBOpcodeTypeSTA, FRBAddressModeZeropageIndirect },
    /* $93 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $94 */ { FRBOpcodeTypeSTY, FRBAddressModeZeropageXIndexed },
    /* $95 */ { FRBOpcodeTypeSTA, FRBAddressModeZeropageXIndexed },
    /* $96 */ { FRBOpcodeTypeSTX, FRBAddressModeZeropageYIndexed },
    /* $97 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $98 */ { FRBOpcodeTypeTYA, FRBAddressModeImplied },
    /* $99 */ { FRBOpcodeTypeSTA, FRBAddressModeAbsoluteYIndexed },
    /* $9A */ { FRBOpcodeTypeTXS, FRBAddressModeImplied },
    /* $9B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $9C */ { FRBOpcodeTypeSTZ, FRBAddressModeAbsolute },
    /* $9D */ { FRBOpcodeTypeSTA, FRBAddressModeAbsoluteXIndexed },
    /* $9E */ { FRBOpcodeTypeSTZ, FRBAddressModeAbsoluteXIndexed },
    /* $9F */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $A0 */ { FRBOpcodeTypeLDY, FRBAddressModeImmediate },
    /* $A1 */ { FRBOpcodeTypeLDA, FRBAddressModeIndirectXIndexed },
    /* $A2 */ { FRBOpcodeTypeLDX, FRBAddressModeImmediate },
    /* $A3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $A4 */ { FRBOpcodeTypeLDY, FRBAddressModeZeropage },
    /* $A5 */ { FRBOpcodeTypeLDA, FRBAddressModeZeropage },
    /* $A6 */ { FRBOpcodeTypeLDX, FRBAddressModeZeropage },
    /* $A7 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $A8 */ { FRBOpcodeTypeTAY, FRBAddressModeImplied },
    /* $A9 */ { FRBOpcodeTypeLDA, FRBAddressModeImmediate },
    /* $AA */ { FRBOpcodeTypeTAX, FRBAddressModeImplied },
    /* $AB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $AC */ { FRBOpcodeTypeLDY, FRBAddressModeAbsolute },
    /* $AD */ { FRBOpcodeTypeLDA, FRBAddressModeAbsolute },
    /* $AE */ { FRBOpcodeTypeLDX, FRBAddressModeAbsolute },
    /* $AF */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $B0 */ { FRBOpcodeTypeBCS, FRBAddressModeRelative },
    /* $B1 */ { FRBOpcodeTypeLDA, FRBAddressModeIndirectYIndexed },
    /* $B2 */ { FRBOpcodeTypeLDA, FRBAddressModeZeropageIndirect },
    /* $B3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $B4 */ { FRBOpcodeTypeLDY, FRBAddressModeZeropageXIndexed },
    /* $B5 */ { FRBOpcodeTypeLDA, FRBAddressModeZeropageXIndexed },
    /* $B6 */ { FRBOpcodeTypeLDX, FRBAddressModeZeropageYIndexed },
    /* $B7 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $B8 */ { FRBOpcodeTypeCLV, FRBAddressModeImplied },
    /* $B9 */ { FRBOpcodeTypeLDA, FRBAddressModeAbsoluteYIndexed },
    /* $BA */ { FRBOpcodeTypeTSX, FRBAddressModeImplied },
    /* $BB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $BC */ { FRBOpcodeTypeLDY, FRBAddressModeAbsoluteXIndexed },
    /* $BD */ { FRBOpcodeTypeLDA, FRBAddressModeAbsoluteXIndexed },
    /* $BE */ { FRBOpcodeTypeLDX, FRBAddressModeAbsoluteYIndexed },
    /* $BF */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $C0 */ { FRBOpcodeTypeCPY, FRBAddressModeImmediate },
    /* $C1 */ { FRBOpcodeTypeCMP, FRBAddressModeIndirectXIndexed },
    /* $C2 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $C3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $C4 */ { FRBOpcodeTypeCPY, FRBAddressModeZeropage },
    /* $C5 */ { FRBOpcodeTypeCMP, FRBAddressModeZeropage },
    /* $C6 */ { FRBOpcodeTypeDEC, FRBAddressModeZeropage },
    /* $C7 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $C8 */ { FRBOpcodeTypeINY, FRBAddressModeImplied },
    /* $C9 */ { FRBOpcodeTypeCMP, FRBAddressModeImmediate },
    /* $CA */ { FRBOpcodeTypeDEX, FRBAddressModeImplied },
    /* $CB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $CC */ { FRBOpcodeTypeCPY, FRBAddressModeAbsolute },
    /* $CD */ { FRBOpcodeTypeCMP, FRBAddressModeAbsolute },
    /* $CE */ { FRBOpcodeTypeDEC, FRBAddressModeAbsolute },
    /* $CF */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $D0 */ { FRBOpcodeTypeBNE, FRBAddressModeRelative },
    /* $D1 */ { FRBOpcodeTypeCMP, FRBAddressModeIndirectYIndexed },
    /* $D2 */ { FRBOpcodeTypeCMP, FRBAddressModeZeropageIndirect },
    /* $D3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $D4 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $D5 */ { FRBOpcodeTypeCMP, FRBAddressModeZeropageXIndexed },
    /* $D6 */ { FRBOpcodeTypeDEC, FRBAddressModeZeropageXIndexed },
    /* $D7 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $D8 */ { FRBOpcodeTypeCLD, FRBAddressModeImplied },
    /* $D9 */ { FRBOpcodeTypeCMP, FRBAddressModeAbsoluteYIndexed },
    /* $DA */ { FRBOpcodeTypePHX, FRBAddressModeImplied },
    /* $DB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $DC */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $DD */ { FRBOpcodeTypeCMP, FRBAddressModeAbsoluteXIndexed },
    /* $DE */ { FRBOpcodeTypeDEC, FRBAddressModeAbsoluteXIndexed },
    /* $DF */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $E0 */ { FRBOpcodeTypeCPX, FRBAddressModeImmediate },
    /* $E1 */ { FRBOpcodeTypeSBC, FRBAddressModeIndirectXIndexed },
    /* $E2 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $E3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $E4 */ { FRBOpcodeTypeCPX, FRBAddressModeZeropage },
    /* $E5 */ { FRBOpcodeTypeSBC, FRBAddressModeZeropage },
    /* $E6 */ { FRBOpcodeTypeINC, FRBAddressModeZeropage },
    /* $E7 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $E8 */ { FRBOpcodeTypeINX, FRBAddressModeImplied },
    /* $E9 */ { FRBOpcodeTypeSBC, FRBAddressModeImmediate },
    /* $EA */ { FRBOpcodeTypeNOP, FRBAddressModeImplied },
    /* $EB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $EC */ { FRBOpcodeTypeCPX, FRBAddressModeAbsolute },
    /* $ED */ { FRBOpcodeTypeSBC, FRBAddressModeAbsolute },
    /* $EE */ { FRBOpcodeTypeINC, FRBAddressModeAbsolute },
    /* $EF */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $F0 */ { FRBOpcodeTypeBEQ, FRBAddressModeRelative },
    /* $F1 */ { FRBOpcodeTypeSBC, FRBAddressModeIndirectYIndexed },
    /* $F2 */ { FRBOpcodeTypeSBC, FRBAddressModeZeropageIndirect },
    /* $F3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $F4 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $F5 */ { FRBOpcodeTypeSBC, FRBAddressModeZeropageXIndexed },
    /* $F6 */ { FRBOpcodeTypeINC, FRBAddressModeZeropageXIndexed },
    /* $F7 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $F8 */ { FRBOpcodeTypeSED, FRBAddressModeImplied },
    /* $F9 */ { FRBOpcodeTypeSBC, FRBAddressModeAbsoluteYIndexed },
    /* $FA */ { FRBOpcodeTypePLX, FRBAddressModeImplied },
    /* $FB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $FC */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $FD */ { FRBOpcodeTypeSBC, FRBAddressModeAbsoluteXIndexed },
    /* $FE */ { FRBOpcodeTypeINC, FRBAddressModeAbsoluteXIndexed },
    /* $FF */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
};

#endif