/*
 Copyright (c) 2014-2017, Alessandro Gatti - frob.it
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#import "FRBGeneric65C02.h"

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedClassInspection"

static const struct FRBOpcode kOpcodeTable[256];

@implementation ItFrobHopper6502Generic65C02

+ (NSString *_Nonnull)family {
  return @"Generic";
}

+ (NSString *_Nonnull)model {
  return @"65c02";
}

+ (BOOL)exported {
  return YES;
}

+ (int)addressSpaceWidth {
  return 16;
}

- (const FRBOpcode *)opcodeForByte:(uint8_t)byte {
  return &kOpcodeTable[byte];
}

@end

static const struct FRBOpcode kOpcodeTable[256] = {
    {FRBOpcodeTypeBRK, FRBAddressModeStack, N, S | P},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPageIndexedIndirect, A | X, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeTSB, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeASL, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypePHP, FRBAddressModeStack, P | S, S},
    {FRBOpcodeTypeORA, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeASL, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeTSB, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeORA, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeASL, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBPL, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirectIndexedY, A | Y, A},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeTRB, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeASL, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCLC, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypeINC, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeTRB, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeASL, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeJSR, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPageIndexedIndirect, A | X, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBIT, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeROL, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypePLP, FRBAddressModeStack, S, P | S},
    {FRBOpcodeTypeAND, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeROL, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBIT, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeAND, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeROL, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBMI, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirectIndexedY, A | Y, A},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBIT, FRBAddressModeZeroPageIndexedX, A | X, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeROL, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSEC, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypeDEC, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBIT, FRBAddressModeAbsoluteIndexedX, A | X, N},
    {FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeROL, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeRTI, FRBAddressModeStack, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndexedIndirect, A | X, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeLSR, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypePHA, FRBAddressModeStack, A | S, S},
    {FRBOpcodeTypeEOR, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeLSR, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeJMP, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeLSR, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBVC, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirectIndexedY, A | Y, A},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeLSR, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCLI, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypePHY, FRBAddressModeStack, Y | S, S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeLSR, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeRTS, FRBAddressModeStack, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPageIndexedIndirect, A | X, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTZ, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeROR, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypePLA, FRBAddressModeStack, S, A | S},
    {FRBOpcodeTypeADC, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeROR, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndirect, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeROR, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBVS, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirectIndexedY, A | Y, A},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTZ, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeROR, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSEI, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypePLY, FRBAddressModeStack, Y, Y | S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndexedIndirect, X, N},
    {FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeROR, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBRA, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndexedIndirect, A | X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTY, FRBAddressModeZeroPage, Y, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeSTX, FRBAddressModeZeroPage, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeDEY, FRBAddressModeImplied, Y, Y},
    {FRBOpcodeTypeBIT, FRBAddressModeImmediate, A, N},
    {FRBOpcodeTypeTXA, FRBAddressModeImplied, A | X, A | X},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTY, FRBAddressModeAbsolute, Y, N},
    {FRBOpcodeTypeSTA, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeSTX, FRBAddressModeAbsolute, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBCC, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirectIndexedY, A | Y, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirect, A, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTY, FRBAddressModeZeroPageIndexedX, X | Y, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndexedX, A | X, N},
    {FRBOpcodeTypeSTX, FRBAddressModeZeroPageIndexedY, X | Y, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeTYA, FRBAddressModeImplied, A | Y, A | Y},
    {FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedY, A | Y, N},
    {FRBOpcodeTypeTXS, FRBAddressModeImplied, X | S, X | S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTZ, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedX, A | X, N},
    {FRBOpcodeTypeSTZ, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeImmediate, N, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedIndirect, X, A},
    {FRBOpcodeTypeLDX, FRBAddressModeImmediate, N, X},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeZeroPage, N, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPage, N, A},
    {FRBOpcodeTypeLDX, FRBAddressModeZeroPage, N, X},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeTAY, FRBAddressModeImplied, A | Y, A | Y},
    {FRBOpcodeTypeLDA, FRBAddressModeImmediate, N, A},
    {FRBOpcodeTypeTAX, FRBAddressModeImplied, A | X, A | X},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeAbsolute, N, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeAbsolute, N, A},
    {FRBOpcodeTypeLDX, FRBAddressModeAbsolute, N, X},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBCS, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndirectIndexedY, Y, A},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndirect, N, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeZeroPageIndexedX, X, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedX, X, A},
    {FRBOpcodeTypeLDX, FRBAddressModeZeroPageIndexedY, Y, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCLV, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedY, Y, A},
    {FRBOpcodeTypeTSX, FRBAddressModeImplied, X | S, X | S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeAbsoluteIndexedX, X, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedX, X, A},
    {FRBOpcodeTypeLDX, FRBAddressModeAbsoluteIndexedY, X, Y},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPY, FRBAddressModeImmediate, Y, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndexedIndirect, A, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPY, FRBAddressModeZeroPage, Y, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeDEC, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeINY, FRBAddressModeImplied, Y, Y},
    {FRBOpcodeTypeCMP, FRBAddressModeImmediate, A, N},
    {FRBOpcodeTypeDEX, FRBAddressModeImplied, X, X},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPY, FRBAddressModeAbsolute, Y, N},
    {FRBOpcodeTypeCMP, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeDEC, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBNE, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirectIndexedY, A | Y, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirect, A, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndexedX, A | X, N},
    {FRBOpcodeTypeDEC, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCLD, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedY, A | Y, N},
    {FRBOpcodeTypePHX, FRBAddressModeStack, X | S, S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedX, A | X, N},
    {FRBOpcodeTypeDEC, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPX, FRBAddressModeImmediate, X, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndexedIndirect, A | X, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPX, FRBAddressModeZeroPage, X, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeINC, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeINX, FRBAddressModeImplied, X, X},
    {FRBOpcodeTypeSBC, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeNOP, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPX, FRBAddressModeAbsolute, X, N},
    {FRBOpcodeTypeSBC, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeINC, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBEQ, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirectIndexedY, A | Y, A},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeINC, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSED, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypePLX, FRBAddressModeStack, X, X | S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeINC, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N}};

#pragma clang diagnostic pop
