/*
 Copyright (c) 2014, Alessandro Gatti - frob.it
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef FRBHuC6280Table_h
#define FRBHuC6280Table_h

#import "FRBBase.h"

static const struct FRBOpcode FRBHuC6280OpcodeTable[256] = {
    /* $00 */ { FRBOpcodeTypeBRK, FRBAddressModeImplied, 0, 0 },
    /* $01 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndexedIndirect },
    /* $02 */ { FRBOpcodeTypeSXY, FRBAddressModeImplied, FRBRegisterIndexX | FRBRegisterIndexY, FRBRegisterIndexX | FRBRegisterIndexY },
    /* $03 */ { FRBOpcodeTypeST0, FRBAddressModeImmediate, 0, 0 },
    /* $04 */ { FRBOpcodeTypeTSB, FRBAddressModeZeroPage, FRBRegisterAccumulator, 0 },
    /* $05 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPage, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $06 */ { FRBOpcodeTypeASL, FRBAddressModeZeroPage, 0, 0 },
    /* $07 */ { FRBOpcodeTypeRMB0, FRBAddressModeZeroPage, 0, 0 },
    /* $08 */ { FRBOpcodeTypePHP, FRBAddressModeStack, 0, 0 }, // TODO
    /* $09 */ { FRBOpcodeTypeORA, FRBAddressModeImmediate, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $0A */ { FRBOpcodeTypeASL, FRBAddressModeAccumulator, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $0B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $0C */ { FRBOpcodeTypeTSB, FRBAddressModeAbsolute, FRBRegisterAccumulator, 0 },
    /* $0D */ { FRBOpcodeTypeORA, FRBAddressModeAbsolute, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $0E */ { FRBOpcodeTypeASL, FRBAddressModeAbsolute, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $0F */ { FRBOpcodeTypeBBR0, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $10 */ { FRBOpcodeTypeBPL, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $11 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $12 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirect, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $13 */ { FRBOpcodeTypeST1, FRBAddressModeImmediate, 0, 0 },
    /* $14 */ { FRBOpcodeTypeTRB, FRBAddressModeZeroPage, FRBRegisterAccumulator, 0 },
    /* $15 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $16 */ { FRBOpcodeTypeASL, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $17 */ { FRBOpcodeTypeRMB1, FRBAddressModeZeroPage, 0, 0 },
    /* $18 */ { FRBOpcodeTypeCLC, FRBAddressModeImplied, 0, 0 },
    /* $19 */ { FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $1A */ { FRBOpcodeTypeINC, FRBAddressModeAccumulator, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $1B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $1C */ { FRBOpcodeTypeTRB, FRBAddressModeAbsolute, FRBRegisterAccumulator, 0 },
    /* $1D */ { FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $1E */ { FRBOpcodeTypeASL, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $1F */ { FRBOpcodeTypeBBR1, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $20 */ { FRBOpcodeTypeJSR, FRBAddressModeAbsolute, 0, 0 },
    /* $21 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndexedIndirect, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $22 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $23 */ { FRBOpcodeTypeST2, FRBAddressModeImmediate, 0, 0 },
    /* $24 */ { FRBOpcodeTypeBIT, FRBAddressModeZeroPage, FRBRegisterAccumulator, 0 },
    /* $25 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPage, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $26 */ { FRBOpcodeTypeROL, FRBAddressModeZeroPage, 0, 0 },
    /* $27 */ { FRBOpcodeTypeRMB2, FRBAddressModeZeroPage, 0, 0 },
    /* $28 */ { FRBOpcodeTypePLP, FRBAddressModeStack, 0, 0 }, // TODO
    /* $29 */ { FRBOpcodeTypeAND, FRBAddressModeImmediate, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $2A */ { FRBOpcodeTypeROL, FRBAddressModeAccumulator, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $2B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $2C */ { FRBOpcodeTypeBIT, FRBAddressModeAbsolute, FRBRegisterAccumulator, 0 },
    /* $2D */ { FRBOpcodeTypeAND, FRBAddressModeAbsolute, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $2E */ { FRBOpcodeTypeROL, FRBAddressModeAbsolute, 0, 0 },
    /* $2F */ { FRBOpcodeTypeBBR2, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $30 */ { FRBOpcodeTypeBMI, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $31 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $32 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirect, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $33 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $34 */ { FRBOpcodeTypeBIT, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, 0 },
    /* $35 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $36 */ { FRBOpcodeTypeROL, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, 0 },
    /* $37 */ { FRBOpcodeTypeRMB3, FRBAddressModeZeroPage, 0, 0 },
    /* $38 */ { FRBOpcodeTypeSEC, FRBAddressModeImplied, 0, 0 },
    /* $39 */ { FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $3A */ { FRBOpcodeTypeDEC, FRBAddressModeAccumulator, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $3B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $3C */ { FRBOpcodeTypeBIT, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, 0 },
    /* $3D */ { FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $3E */ { FRBOpcodeTypeROL, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, 0 },
    /* $3F */ { FRBOpcodeTypeBBR3, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $40 */ { FRBOpcodeTypeRTI, FRBAddressModeStack, 0, 0 },
    /* $41 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndexedIndirect, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $42 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $43 */ { FRBOpcodeTypeTMA, FRBAddressModeImmediate, 0, FRBRegisterAccumulator },
    /* $44 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $45 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPage, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $46 */ { FRBOpcodeTypeLSR, FRBAddressModeZeroPage, 0, 0 },
    /* $47 */ { FRBOpcodeTypeRMB4, FRBAddressModeZeroPage, 0, 0 },
    /* $48 */ { FRBOpcodeTypePHA, FRBAddressModeStack, 0, 0 }, // TODO
    /* $49 */ { FRBOpcodeTypeEOR, FRBAddressModeImmediate, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $4A */ { FRBOpcodeTypeLSR, FRBAddressModeAccumulator, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $4B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $4C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsolute, 0, 0 },
    /* $4D */ { FRBOpcodeTypeEOR, FRBAddressModeAbsolute, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $4E */ { FRBOpcodeTypeLSR, FRBAddressModeAbsolute, 0, 0 },
    /* $4F */ { FRBOpcodeTypeBBR4, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $50 */ { FRBOpcodeTypeBVC, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $51 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $52 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirect, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $53 */ { FRBOpcodeTypeTAM, FRBAddressModeImmediate, FRBRegisterAccumulator, 0 },
    /* $54 */ { FRBOpcodeTypeCSL, FRBAddressModeImplied, 0, 0 },
    /* $55 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $56 */ { FRBOpcodeTypeLSR, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, 0 },
    /* $57 */ { FRBOpcodeTypeRMB5, FRBAddressModeZeroPage, 0, 0 },
    /* $58 */ { FRBOpcodeTypeCLI, FRBAddressModeImplied, 0, 0 },
    /* $59 */ { FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $5A */ { FRBOpcodeTypePHY, FRBAddressModeStack, FRBRegisterIndexY, 0 }, // TODO
    /* $5B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $5C */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $5D */ { FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $5E */ { FRBOpcodeTypeLSR, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, 0 },
    /* $5F */ { FRBOpcodeTypeBBR5, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $60 */ { FRBOpcodeTypeRTS, FRBAddressModeStack, 0, 0 },
    /* $61 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndexedIndirect, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $62 */ { FRBOpcodeTypeCLA, FRBAddressModeImplied, 0, FRBRegisterAccumulator },
    /* $63 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $64 */ { FRBOpcodeTypeSTZ, FRBAddressModeZeroPage, 0, 0 },
    /* $65 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPage, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $66 */ { FRBOpcodeTypeROR, FRBAddressModeZeroPage, 0, 0 },
    /* $67 */ { FRBOpcodeTypeRMB6, FRBAddressModeZeroPage, 0, 0 },
    /* $68 */ { FRBOpcodeTypePLA, FRBAddressModeStack, 0, 0 }, // TODO
    /* $69 */ { FRBOpcodeTypeADC, FRBAddressModeImmediate, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $6A */ { FRBOpcodeTypeROR, FRBAddressModeAccumulator, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $6B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $6C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndirect, 0, 0 },
    /* $6D */ { FRBOpcodeTypeADC, FRBAddressModeAbsolute, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $6E */ { FRBOpcodeTypeROR, FRBAddressModeAbsolute, 0, 0 },
    /* $6F */ { FRBOpcodeTypeBBR6, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $70 */ { FRBOpcodeTypeBVS, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $71 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $72 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirect, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $73 */ { FRBOpcodeTypeTII, FRBAddressModeBlockTransfer, 0, 0 },
    /* $74 */ { FRBOpcodeTypeSTZ, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, 0 },
    /* $75 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $76 */ { FRBOpcodeTypeROR, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, 0 },
    /* $77 */ { FRBOpcodeTypeRMB7, FRBAddressModeZeroPage, 0, 0 },
    /* $78 */ { FRBOpcodeTypeSEI, FRBAddressModeImplied, 0, 0 },
    /* $79 */ { FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $7A */ { FRBOpcodeTypePLY, FRBAddressModeStack, FRBRegisterIndexY, 0 }, // TODO
    /* $7B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $7C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndexedIndirect, FRBRegisterIndexX, 0 },
    /* $7D */ { FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $7E */ { FRBOpcodeTypeROR, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, 0 },
    /* $7F */ { FRBOpcodeTypeBBR7, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $80 */ { FRBOpcodeTypeBRA, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $81 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndexedIndirect, FRBRegisterAccumulator | FRBRegisterIndexX, 0 },
    /* $82 */ { FRBOpcodeTypeCLX, FRBAddressModeImplied, 0, FRBRegisterIndexX },
    /* $83 */ { FRBOpcodeTypeTST, FRBAddressModeImmediateZeroPage, 0, 0 },
    /* $84 */ { FRBOpcodeTypeSTY, FRBAddressModeZeroPage, FRBRegisterIndexY, 0 },
    /* $85 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPage, FRBRegisterAccumulator, 0 },
    /* $86 */ { FRBOpcodeTypeSTX, FRBAddressModeZeroPage, FRBRegisterIndexX, 0 },
    /* $87 */ { FRBOpcodeTypeSMB0, FRBAddressModeZeroPage, 0, 0 },
    /* $88 */ { FRBOpcodeTypeDEY, FRBAddressModeImplied, FRBRegisterIndexY, FRBRegisterIndexY },
    /* $89 */ { FRBOpcodeTypeBIT, FRBAddressModeImmediate, FRBRegisterAccumulator, 0 },
    /* $8A */ { FRBOpcodeTypeTXA, FRBAddressModeImplied, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator | FRBRegisterIndexX },
    /* $8B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $8C */ { FRBOpcodeTypeSTY, FRBAddressModeAbsolute, FRBRegisterIndexY, 0 },
    /* $8D */ { FRBOpcodeTypeSTA, FRBAddressModeAbsolute, FRBRegisterAccumulator, 0 },
    /* $8E */ { FRBOpcodeTypeSTX, FRBAddressModeAbsolute, FRBRegisterIndexX, 0 },
    /* $8F */ { FRBOpcodeTypeBBS0, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $90 */ { FRBOpcodeTypeBCC, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $91 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, 0 },
    /* $92 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirect, FRBRegisterAccumulator, 0 },
    /* $93 */ { FRBOpcodeTypeTST, FRBAddressModeImmediateAbsolute, 0, 0 },
    /* $94 */ { FRBOpcodeTypeSTY, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX | FRBRegisterIndexY, 0 },
    /* $95 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, 0 },
    /* $96 */ { FRBOpcodeTypeSTX, FRBAddressModeZeroPageIndexedY, FRBRegisterIndexX | FRBRegisterIndexY, 0 },
    /* $97 */ { FRBOpcodeTypeSMB1, FRBAddressModeZeroPage, 0, 0 },
    /* $98 */ { FRBOpcodeTypeTYA, FRBAddressModeImplied, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator | FRBRegisterIndexY },
    /* $99 */ { FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, 0 },
    /* $9A */ { FRBOpcodeTypeTXS, FRBAddressModeImplied, FRBRegisterIndexX, FRBRegisterIndexX }, // TODO
    /* $9B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $9C */ { FRBOpcodeTypeSTZ, FRBAddressModeAbsolute, 0, 0 },
    /* $9D */ { FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, 0 },
    /* $9E */ { FRBOpcodeTypeSTZ, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, 0 },
    /* $9F */ { FRBOpcodeTypeBBS1, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $A0 */ { FRBOpcodeTypeLDY, FRBAddressModeImmediate, 0, FRBRegisterIndexY },
    /* $A1 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedIndirect, FRBRegisterIndexX, FRBRegisterAccumulator},
    /* $A2 */ { FRBOpcodeTypeLDX, FRBAddressModeImmediate, 0, FRBRegisterIndexX },
    /* $A3 */ { FRBOpcodeTypeTST, FRBAddressModeImmediateZeroPageX, FRBRegisterIndexX, 0 },
    /* $A4 */ { FRBOpcodeTypeLDY, FRBAddressModeZeroPage, 0, FRBRegisterIndexY },
    /* $A5 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPage, 0, FRBRegisterAccumulator },
    /* $A6 */ { FRBOpcodeTypeLDX, FRBAddressModeZeroPage, 0, FRBRegisterIndexX },
    /* $A7 */ { FRBOpcodeTypeSMB2, FRBAddressModeZeroPage, 0, 0 },
    /* $A8 */ { FRBOpcodeTypeTAY, FRBAddressModeImplied, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator | FRBRegisterIndexY },
    /* $A9 */ { FRBOpcodeTypeLDA, FRBAddressModeImmediate, 0, FRBRegisterAccumulator },
    /* $AA */ { FRBOpcodeTypeTAX, FRBAddressModeImplied, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator | FRBRegisterIndexX },
    /* $AB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $AC */ { FRBOpcodeTypeLDY, FRBAddressModeAbsolute, 0, FRBRegisterIndexY },
    /* $AD */ { FRBOpcodeTypeLDA, FRBAddressModeAbsolute, 0, FRBRegisterAccumulator },
    /* $AE */ { FRBOpcodeTypeLDX, FRBAddressModeAbsolute, 0, FRBRegisterIndexX },
    /* $AF */ { FRBOpcodeTypeBBS2, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $B0 */ { FRBOpcodeTypeBCS, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $B1 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $B2 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndirect, 0, FRBRegisterAccumulator },
    /* $B3 */ { FRBOpcodeTypeTST, FRBAddressModeImmediateAbsoluteX, FRBRegisterIndexX, 0 },
    /* $B4 */ { FRBOpcodeTypeLDY, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, FRBRegisterIndexY },
    /* $B5 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $B6 */ { FRBOpcodeTypeLDX, FRBAddressModeZeroPageIndexedY, FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $B7 */ { FRBOpcodeTypeSMB3, FRBAddressModeZeroPage, 0, 0 },
    /* $B8 */ { FRBOpcodeTypeCLV, FRBAddressModeImplied, 0, 0 },
    /* $B9 */ { FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedY, FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $BA */ { FRBOpcodeTypeTSX, FRBAddressModeImplied, FRBRegisterIndexX, FRBRegisterIndexX }, // TODO
    /* $BB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $BC */ { FRBOpcodeTypeLDY, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, FRBRegisterIndexY },
    /* $BD */ { FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $BE */ { FRBOpcodeTypeLDX, FRBAddressModeAbsoluteIndexedY, FRBRegisterIndexX, FRBRegisterIndexY },
    /* $BF */ { FRBOpcodeTypeBBS3, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $C0 */ { FRBOpcodeTypeCPY, FRBAddressModeImmediate, FRBRegisterIndexY, 0 },
    /* $C1 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndexedIndirect, FRBRegisterAccumulator, 0 },
    /* $C2 */ { FRBOpcodeTypeCLY, FRBAddressModeImplied, 0, FRBRegisterIndexY },
    /* $C3 */ { FRBOpcodeTypeTDD, FRBAddressModeBlockTransfer, 0, 0 },
    /* $C4 */ { FRBOpcodeTypeCPY, FRBAddressModeZeroPage, FRBRegisterIndexY, 0 },
    /* $C5 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPage, FRBRegisterAccumulator, 0 },
    /* $C6 */ { FRBOpcodeTypeDEC, FRBAddressModeZeroPage, 0, 0 },
    /* $C7 */ { FRBOpcodeTypeSMB4, FRBAddressModeZeroPage, 0, 0 },
    /* $C8 */ { FRBOpcodeTypeINY, FRBAddressModeImplied, FRBRegisterIndexY, FRBRegisterIndexY },
    /* $C9 */ { FRBOpcodeTypeCMP, FRBAddressModeImmediate, FRBRegisterAccumulator, 0 },
    /* $CA */ { FRBOpcodeTypeDEX, FRBAddressModeImplied, FRBRegisterIndexX, FRBRegisterIndexX },
    /* $CB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $CC */ { FRBOpcodeTypeCPY, FRBAddressModeAbsolute, FRBRegisterIndexY, 0 },
    /* $CD */ { FRBOpcodeTypeCMP, FRBAddressModeAbsolute, FRBRegisterAccumulator, 0 },
    /* $CE */ { FRBOpcodeTypeDEC, FRBAddressModeAbsolute, 0, 0 },
    /* $CF */ { FRBOpcodeTypeBBS4, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $D0 */ { FRBOpcodeTypeBNE, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $D1 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, 0 },
    /* $D2 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirect, FRBRegisterAccumulator, 0 },
    /* $D3 */ { FRBOpcodeTypeTIN, FRBAddressModeBlockTransfer, 0, 0 },
    /* $D4 */ { FRBOpcodeTypeCSH, FRBAddressModeImplied, 0, 0 },
    /* $D5 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, 0 },
    /* $D6 */ { FRBOpcodeTypeDEC, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, FRBRegisterIndexX },
    /* $D7 */ { FRBOpcodeTypeSMB5, FRBAddressModeZeroPage, 0, 0 },
    /* $D8 */ { FRBOpcodeTypeCLD, FRBAddressModeImplied, 0, 0 },
    /* $D9 */ { FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, 0 },
    /* $DA */ { FRBOpcodeTypePHX, FRBAddressModeStack, FRBRegisterIndexX, 0 }, // TODO
    /* $DB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $DC */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $DD */ { FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, 0 },
    /* $DE */ { FRBOpcodeTypeDEC, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, 0 },
    /* $DF */ { FRBOpcodeTypeBBS5, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $E0 */ { FRBOpcodeTypeCPX, FRBAddressModeImmediate, FRBRegisterIndexX, 0 },
    /* $E1 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndexedIndirect, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $E2 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $E3 */ { FRBOpcodeTypeTIA, FRBAddressModeBlockTransfer, 0, 0 },
    /* $E4 */ { FRBOpcodeTypeCPX, FRBAddressModeZeroPage, FRBRegisterIndexX, 0 },
    /* $E5 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPage, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $E6 */ { FRBOpcodeTypeINC, FRBAddressModeZeroPage, 0, 0 },
    /* $E7 */ { FRBOpcodeTypeSMB6, FRBAddressModeZeroPage, 0, 0 },
    /* $E8 */ { FRBOpcodeTypeINX, FRBAddressModeImplied, FRBRegisterIndexX, FRBRegisterIndexX },
    /* $E9 */ { FRBOpcodeTypeSBC, FRBAddressModeImmediate, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $EA */ { FRBOpcodeTypeNOP, FRBAddressModeImplied, 0, 0 },
    /* $EB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $EC */ { FRBOpcodeTypeCPX, FRBAddressModeAbsolute, FRBRegisterIndexX, 0 },
    /* $ED */ { FRBOpcodeTypeSBC, FRBAddressModeAbsolute, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $EE */ { FRBOpcodeTypeINC, FRBAddressModeAbsolute, 0, 0 },
    /* $EF */ { FRBOpcodeTypeBBS6, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },

    /* $F0 */ { FRBOpcodeTypeBEQ, FRBAddressModeProgramCounterRelative, 0, 0 },
    /* $F1 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirectIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $F2 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirect, FRBRegisterAccumulator, FRBRegisterAccumulator },
    /* $F3 */ { FRBOpcodeTypeTAI, FRBAddressModeBlockTransfer, 0, 0 },
    /* $F4 */ { FRBOpcodeTypeSET, FRBAddressModeImplied, 0, 0 },
    /* $F5 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $F6 */ { FRBOpcodeTypeINC, FRBAddressModeZeroPageIndexedX, FRBRegisterIndexX, 0 },
    /* $F7 */ { FRBOpcodeTypeSMB7, FRBAddressModeZeroPage, 0, 0 },
    /* $F8 */ { FRBOpcodeTypeSED, FRBAddressModeImplied, 0, 0 },
    /* $F9 */ { FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedY, FRBRegisterAccumulator | FRBRegisterIndexY, FRBRegisterAccumulator },
    /* $FA */ { FRBOpcodeTypePLX, FRBAddressModeStack, FRBRegisterIndexX, 0 }, // TODO
    /* $FB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $FC */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, 0, 0 },
    /* $FD */ { FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedX, FRBRegisterAccumulator | FRBRegisterIndexX, FRBRegisterAccumulator },
    /* $FE */ { FRBOpcodeTypeINC, FRBAddressModeAbsoluteIndexedX, FRBRegisterIndexX, 0 },
    /* $FF */ { FRBOpcodeTypeBBS7, FRBAddressModeZeroPageProgramCounterRelative, 0, 0 },
};

#endif