/*
 Copyright (c) 2014-2017, Alessandro Gatti - frob.it
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#import "FRBR65C19.h"
#import "FRBBase.h"

#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedClassInspection"

static const struct FRBOpcode kOpcodeTable[256];

@implementation ItFrobHopper6502R65C19

+ (NSString *_Nonnull)family {
  return @"Rockwell";
}

+ (NSString *_Nonnull)model {
  return @"R65C19";
}

+ (BOOL)exported {
  return YES;
}

+ (int)addressSpaceWidth {
  return 16;
}

- (const FRBOpcode *)opcodeForByte:(uint8_t)byte {
  return &kOpcodeTable[byte];
}

@end

static const struct FRBOpcode kOpcodeTable[256] = {
    {FRBOpcodeTypeBRK, FRBAddressModeStack, N, S | P},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeMPY, FRBAddressModeImplied, A | Y, A | Y},
    {FRBOpcodeTypeTIP, FRBAddressModeImplied, I, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeASL, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeRMB0, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypePHP, FRBAddressModeStack, P | S, S},
    {FRBOpcodeTypeORA, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeASL, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeJSB0, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeJPI, FRBAddressModeAbsolute, I, I},
    {FRBOpcodeTypeORA, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeASL, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeBBR0, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBPL, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirectIndexedX, A | X, A},
    {FRBOpcodeTypeMPA, FRBAddressModeImplied, A | W | Y, W},
    {FRBOpcodeTypeLAB, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeORA, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeASL, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeRMB1, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeCLC, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypeNEG, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeJSB1, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeASL, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeBBR1, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeJSR, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypePSH, FRBAddressModeImplied, A | X | Y, S},
    {FRBOpcodeTypePHW, FRBAddressModeImplied, W, S},
    {FRBOpcodeTypeBIT, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeROL, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeRMB2, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypePLP, FRBAddressModeStack, S, P | S},
    {FRBOpcodeTypeAND, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeROL, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeJSB2, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeBIT, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeAND, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeROL, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeBBR2, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBMI, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirectIndexedX, A | X, A},
    {FRBOpcodeTypePUL, FRBAddressModeImplied, S, A | X | Y},
    {FRBOpcodeTypePLW, FRBAddressModeImplied, S, S | W},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeROL, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeRMB3, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeSEC, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypeASR, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeJSB3, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeROL, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeBBR3, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeRTI, FRBAddressModeStack, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeRND, FRBAddressModeImplied, W, A | W},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeLSR, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeRMB4, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypePHA, FRBAddressModeStack, A | S, S},
    {FRBOpcodeTypeEOR, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeLSR, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeJSB4, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeJMP, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeLSR, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeBBR4, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBVC, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirectIndexedX, A | X, A},
    {FRBOpcodeTypeCLW, FRBAddressModeImplied, N, W},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeLSR, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeRMB5, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeCLI, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypePHY, FRBAddressModeStack, Y | S, S},
    {FRBOpcodeTypeJSB5, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeLSR, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeBBR5, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeRTS, FRBAddressModeStack, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeTAW, FRBAddressModeImplied, A | W, A | W},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeADD, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeROR, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeRMB6, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypePLA, FRBAddressModeStack, S, A | S},
    {FRBOpcodeTypeADC, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeROR, FRBAddressModeAccumulator, A, A},
    {FRBOpcodeTypeJSB6, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndirect, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeROR, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeBBR6, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBVS, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirectIndexedX, A | X, A},
    {FRBOpcodeTypeTWA, FRBAddressModeImplied, A | W, A | W},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeADD, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeADC, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeROR, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeRMB7, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeSEI, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypePLY, FRBAddressModeStack, S, Y | S},
    {FRBOpcodeTypeJSB7, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndexedIndirect, X, N},
    {FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeROR, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeBBR7, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBRA, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirect, A, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTY, FRBAddressModeZeroPage, Y, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeSTX, FRBAddressModeZeroPage, X, N},
    {FRBOpcodeTypeSMB0, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeDEY, FRBAddressModeImplied, Y, Y},
    {FRBOpcodeTypeADD, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeTXA, FRBAddressModeImplied, A | X, A | X},
    {FRBOpcodeTypeNXT, FRBAddressModeImplied, I, I},
    {FRBOpcodeTypeSTY, FRBAddressModeAbsolute, Y, N},
    {FRBOpcodeTypeSTA, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeSTX, FRBAddressModeAbsolute, X, N},
    {FRBOpcodeTypeBBS0, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBCC, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirectIndexedX, A | X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTY, FRBAddressModeZeroPageIndexedX, X | Y, N},
    {FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndexedX, A | X, N},
    {FRBOpcodeTypeSTX, FRBAddressModeZeroPageIndexedY, X | Y, N},
    {FRBOpcodeTypeSMB1, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeTYA, FRBAddressModeImplied, A | Y, A | Y},
    {FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedY, A | Y, N},
    {FRBOpcodeTypeTXS, FRBAddressModeImplied, X | S, X | S},
    {FRBOpcodeTypeLII, FRBAddressModeImplied, I, I},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedX, A | X, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeBBS1, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeImmediate, N, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedIndirect, X, A},
    {FRBOpcodeTypeLDX, FRBAddressModeImmediate, N, X},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeZeroPage, N, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPage, N, A},
    {FRBOpcodeTypeLDX, FRBAddressModeZeroPage, N, X},
    {FRBOpcodeTypeSMB2, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeTAY, FRBAddressModeImplied, A | Y, A | Y},
    {FRBOpcodeTypeLDA, FRBAddressModeImmediate, N, A},
    {FRBOpcodeTypeTAX, FRBAddressModeImplied, A | X, A | X},
    {FRBOpcodeTypeLAN, FRBAddressModeImplied, I, A | I},
    {FRBOpcodeTypeLDY, FRBAddressModeAbsolute, N, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeAbsolute, N, A},
    {FRBOpcodeTypeLDX, FRBAddressModeAbsolute, N, X},
    {FRBOpcodeTypeBBS2, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBCS, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndirectIndexedX, X, A},
    {FRBOpcodeTypeSTI, FRBAddressModeZeroPage, I, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeLDY, FRBAddressModeZeroPageIndexedX, X, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedX, X, A},
    {FRBOpcodeTypeLDX, FRBAddressModeZeroPageIndexedY, Y, A},
    {FRBOpcodeTypeSMB3, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeCLV, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedY, Y, A},
    {FRBOpcodeTypeTSX, FRBAddressModeImplied, X | S, X | S},
    {FRBOpcodeTypeINI, FRBAddressModeImplied, I, I},
    {FRBOpcodeTypeLDY, FRBAddressModeAbsoluteIndexedX, X, Y},
    {FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedX, X, A},
    {FRBOpcodeTypeLDX, FRBAddressModeAbsoluteIndexedY, X, Y},
    {FRBOpcodeTypeBBS3, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeCPY, FRBAddressModeImmediate, Y, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirect, A, N},
    {FRBOpcodeTypeRBA, FRBAddressModeImmediateAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPY, FRBAddressModeZeroPage, Y, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPage, A, N},
    {FRBOpcodeTypeDEC, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeSMB4, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeINY, FRBAddressModeImplied, Y, Y},
    {FRBOpcodeTypeCMP, FRBAddressModeImmediate, A, N},
    {FRBOpcodeTypeDEX, FRBAddressModeImplied, X, X},
    {FRBOpcodeTypePHI, FRBAddressModeStack, I, I | S},
    {FRBOpcodeTypeCPY, FRBAddressModeAbsolute, Y, N},
    {FRBOpcodeTypeCMP, FRBAddressModeAbsolute, A, N},
    {FRBOpcodeTypeDEC, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeBBS4, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBNE, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirectIndexedX, A | X, N},
    {FRBOpcodeTypeSBA, FRBAddressModeImmediateAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeEXC, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndexedX, A | X, N},
    {FRBOpcodeTypeDEC, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeSMB5, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeCLD, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedY, A | Y, N},
    {FRBOpcodeTypePHX, FRBAddressModeStack, X | S, S},
    {FRBOpcodeTypePLI, FRBAddressModeImplied, S, I | S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedX, A | X, N},
    {FRBOpcodeTypeDEC, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeBBS5, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeCPX, FRBAddressModeImmediate, X, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirect, A, A},
    {FRBOpcodeTypeBAR, FRBAddressModeBitsProgramCounterAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeCPX, FRBAddressModeZeroPage, X, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPage, A, A},
    {FRBOpcodeTypeINC, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeSMB6, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeINX, FRBAddressModeImplied, X, X},
    {FRBOpcodeTypeSBC, FRBAddressModeImmediate, A, A},
    {FRBOpcodeTypeNOP, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeLAI, FRBAddressModeImplied, I, A},
    {FRBOpcodeTypeCPX, FRBAddressModeAbsolute, X, N},
    {FRBOpcodeTypeSBC, FRBAddressModeAbsolute, A, A},
    {FRBOpcodeTypeINC, FRBAddressModeAbsolute, N, N},
    {FRBOpcodeTypeBBS6, FRBAddressModeZeroPageProgramCounterRelative, N, N},
    {FRBOpcodeTypeBEQ, FRBAddressModeProgramCounterRelative, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirectIndexedX, A | X, A},
    {FRBOpcodeTypeBAS, FRBAddressModeBitsProgramCounterAbsolute, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndexedX, A | X, A},
    {FRBOpcodeTypeINC, FRBAddressModeZeroPageIndexedX, X, N},
    {FRBOpcodeTypeSMB7, FRBAddressModeZeroPage, N, N},
    {FRBOpcodeTypeSED, FRBAddressModeImplied, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedY, A | Y, A},
    {FRBOpcodeTypePLX, FRBAddressModeStack, S, X | S},
    {FRBOpcodeTypePIA, FRBAddressModeImplied, I | S, A | I | S},
    {FRBOpcodeTypeUndocumented, FRBAddressModeUnknown, N, N},
    {FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedX, A | X, A},
    {FRBOpcodeTypeINC, FRBAddressModeAbsoluteIndexedX, X, N},
    {FRBOpcodeTypeBBS7, FRBAddressModeZeroPageProgramCounterRelative, N, N}};

#pragma clang diagnostic pop
