/*
 Copyright (c) 2014, Alessandro Gatti - frob.it
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef FRBR6500Table_h
#define FRBR6500Table_h

#import "FRBBase.h"

static const struct FRBOpcode FRBR6500OpcodeTable[256] = {
    /* $00 */ { FRBOpcodeTypeBRK, FRBAddressModeImplied },
    /* $01 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndexedIndirect },
    /* $02 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $03 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $04 */ { FRBOpcodeTypeTSB, FRBAddressModeZeroPage },
    /* $05 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPage },
    /* $06 */ { FRBOpcodeTypeASL, FRBAddressModeZeroPage },
    /* $07 */ { FRBOpcodeTypeRMB0, FRBAddressModeZeroPage },
    /* $08 */ { FRBOpcodeTypePHP, FRBAddressModeStack },
    /* $09 */ { FRBOpcodeTypeORA, FRBAddressModeImmediate },
    /* $0A */ { FRBOpcodeTypeASL, FRBAddressModeAccumulator },
    /* $0B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $0C */ { FRBOpcodeTypeTSB, FRBAddressModeAbsolute },
    /* $0D */ { FRBOpcodeTypeORA, FRBAddressModeAbsolute },
    /* $0E */ { FRBOpcodeTypeASL, FRBAddressModeAbsolute },
    /* $0F */ { FRBOpcodeTypeBBR0, FRBAddressModeZeroPageProgramCounterRelative },

    /* $10 */ { FRBOpcodeTypeBPL, FRBAddressModeProgramCounterRelative },
    /* $11 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirectIndexedY },
    /* $12 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndirect },
    /* $13 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $14 */ { FRBOpcodeTypeTRB, FRBAddressModeZeroPage },
    /* $15 */ { FRBOpcodeTypeORA, FRBAddressModeZeroPageIndexedX },
    /* $16 */ { FRBOpcodeTypeASL, FRBAddressModeZeroPageIndexedX },
    /* $17 */ { FRBOpcodeTypeRMB1, FRBAddressModeZeroPage },
    /* $18 */ { FRBOpcodeTypeCLC, FRBAddressModeImplied },
    /* $19 */ { FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedY },
    /* $1A */ { FRBOpcodeTypeINC, FRBAddressModeAccumulator },
    /* $1B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $1C */ { FRBOpcodeTypeTRB, FRBAddressModeAbsolute },
    /* $1D */ { FRBOpcodeTypeORA, FRBAddressModeAbsoluteIndexedX },
    /* $1E */ { FRBOpcodeTypeASL, FRBAddressModeAbsoluteIndexedX },
    /* $1F */ { FRBOpcodeTypeBBR1, FRBAddressModeZeroPageProgramCounterRelative },

    /* $20 */ { FRBOpcodeTypeJSR, FRBAddressModeAbsolute },
    /* $21 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndexedIndirect },
    /* $22 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $23 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $24 */ { FRBOpcodeTypeBIT, FRBAddressModeZeroPage },
    /* $25 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPage },
    /* $26 */ { FRBOpcodeTypeROL, FRBAddressModeZeroPage },
    /* $27 */ { FRBOpcodeTypeRMB2, FRBAddressModeZeroPage },
    /* $28 */ { FRBOpcodeTypePLP, FRBAddressModeStack },
    /* $29 */ { FRBOpcodeTypeAND, FRBAddressModeImmediate },
    /* $2A */ { FRBOpcodeTypeROL, FRBAddressModeAccumulator },
    /* $2B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $2C */ { FRBOpcodeTypeBIT, FRBAddressModeAbsolute },
    /* $2D */ { FRBOpcodeTypeAND, FRBAddressModeAbsolute },
    /* $2E */ { FRBOpcodeTypeROL, FRBAddressModeAbsolute },
    /* $2F */ { FRBOpcodeTypeBBR2, FRBAddressModeZeroPageProgramCounterRelative },

    /* $30 */ { FRBOpcodeTypeBMI, FRBAddressModeProgramCounterRelative },
    /* $31 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirectIndexedY },
    /* $32 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndirect },
    /* $33 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $34 */ { FRBOpcodeTypeBIT, FRBAddressModeZeroPageIndexedX },
    /* $35 */ { FRBOpcodeTypeAND, FRBAddressModeZeroPageIndexedX },
    /* $36 */ { FRBOpcodeTypeROL, FRBAddressModeZeroPageIndexedX },
    /* $37 */ { FRBOpcodeTypeRMB3, FRBAddressModeZeroPage },
    /* $38 */ { FRBOpcodeTypeSEC, FRBAddressModeImmediate },
    /* $39 */ { FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedY },
    /* $3A */ { FRBOpcodeTypeDEC, FRBAddressModeAccumulator },
    /* $3B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $3C */ { FRBOpcodeTypeBIT, FRBAddressModeAbsoluteIndexedX },
    /* $3D */ { FRBOpcodeTypeAND, FRBAddressModeAbsoluteIndexedX },
    /* $3E */ { FRBOpcodeTypeROL, FRBAddressModeAbsoluteIndexedX },
    /* $3F */ { FRBOpcodeTypeBBR3, FRBAddressModeZeroPageProgramCounterRelative },

    /* $40 */ { FRBOpcodeTypeRTI, FRBAddressModeStack },
    /* $41 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndexedIndirect },
    /* $42 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $43 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $44 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $45 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPage },
    /* $46 */ { FRBOpcodeTypeLSR, FRBAddressModeZeroPage },
    /* $47 */ { FRBOpcodeTypeRMB4, FRBAddressModeZeroPage },
    /* $48 */ { FRBOpcodeTypePHA, FRBAddressModeStack },
    /* $49 */ { FRBOpcodeTypeEOR, FRBAddressModeImmediate },
    /* $4A */ { FRBOpcodeTypeLSR, FRBAddressModeAccumulator },
    /* $4B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $4C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsolute },
    /* $4D */ { FRBOpcodeTypeEOR, FRBAddressModeAbsolute },
    /* $4E */ { FRBOpcodeTypeLSR, FRBAddressModeAbsolute },
    /* $4F */ { FRBOpcodeTypeBBR4, FRBAddressModeZeroPageProgramCounterRelative },

    /* $50 */ { FRBOpcodeTypeBVC, FRBAddressModeProgramCounterRelative },
    /* $51 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirectIndexedY },
    /* $52 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndirect },
    /* $53 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $54 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $55 */ { FRBOpcodeTypeEOR, FRBAddressModeZeroPageIndexedX },
    /* $56 */ { FRBOpcodeTypeLSR, FRBAddressModeZeroPageIndexedX },
    /* $57 */ { FRBOpcodeTypeRMB5, FRBAddressModeZeroPage },
    /* $58 */ { FRBOpcodeTypeCLI, FRBAddressModeImplied },
    /* $59 */ { FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedY },
    /* $5A */ { FRBOpcodeTypePHY, FRBAddressModeStack },
    /* $5B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $5C */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $5D */ { FRBOpcodeTypeEOR, FRBAddressModeAbsoluteIndexedX },
    /* $5E */ { FRBOpcodeTypeLSR, FRBAddressModeAbsoluteIndexedX },
    /* $5F */ { FRBOpcodeTypeBBR5, FRBAddressModeZeroPageProgramCounterRelative },

    /* $60 */ { FRBOpcodeTypeRTS, FRBAddressModeStack },
    /* $61 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndexedIndirect },
    /* $62 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $63 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $64 */ { FRBOpcodeTypeSTZ, FRBAddressModeZeroPage },
    /* $65 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPage },
    /* $66 */ { FRBOpcodeTypeROR, FRBAddressModeZeroPage },
    /* $67 */ { FRBOpcodeTypeRMB6, FRBAddressModeZeroPage },
    /* $68 */ { FRBOpcodeTypePLA, FRBAddressModeStack },
    /* $69 */ { FRBOpcodeTypeADC, FRBAddressModeImmediate },
    /* $6A */ { FRBOpcodeTypeROR, FRBAddressModeAccumulator },
    /* $6B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $6C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndirect },
    /* $6D */ { FRBOpcodeTypeADC, FRBAddressModeAbsolute },
    /* $6E */ { FRBOpcodeTypeROR, FRBAddressModeAbsolute },
    /* $6F */ { FRBOpcodeTypeBBR6, FRBAddressModeZeroPageProgramCounterRelative },

    /* $70 */ { FRBOpcodeTypeBVS, FRBAddressModeProgramCounterRelative },
    /* $71 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirectIndexedY },
    /* $72 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndirect },
    /* $73 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $74 */ { FRBOpcodeTypeSTZ, FRBAddressModeZeroPageIndexedX },
    /* $75 */ { FRBOpcodeTypeADC, FRBAddressModeZeroPageIndexedX },
    /* $76 */ { FRBOpcodeTypeROR, FRBAddressModeZeroPageIndexedX },
    /* $77 */ { FRBOpcodeTypeRMB7, FRBAddressModeZeroPage },
    /* $78 */ { FRBOpcodeTypeSEI, FRBAddressModeImplied },
    /* $79 */ { FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedY },
    /* $7A */ { FRBOpcodeTypePLY, FRBAddressModeStack },
    /* $7B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $7C */ { FRBOpcodeTypeJMP, FRBAddressModeAbsoluteIndexedIndirect },
    /* $7D */ { FRBOpcodeTypeADC, FRBAddressModeAbsoluteIndexedX },
    /* $7E */ { FRBOpcodeTypeROR, FRBAddressModeAbsoluteIndexedX },
    /* $7F */ { FRBOpcodeTypeBBR7, FRBAddressModeZeroPageProgramCounterRelative },

    /* $80 */ { FRBOpcodeTypeBRA, FRBAddressModeProgramCounterRelative },
    /* $81 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndexedIndirect },
    /* $82 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $83 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $84 */ { FRBOpcodeTypeSTY, FRBAddressModeZeroPage },
    /* $85 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPage },
    /* $86 */ { FRBOpcodeTypeSTX, FRBAddressModeZeroPage },
    /* $87 */ { FRBOpcodeTypeSMB0, FRBAddressModeZeroPage },
    /* $88 */ { FRBOpcodeTypeDEY, FRBAddressModeImplied },
    /* $89 */ { FRBOpcodeTypeBIT, FRBAddressModeImmediate },
    /* $8A */ { FRBOpcodeTypeTXA, FRBAddressModeImplied },
    /* $8B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $8C */ { FRBOpcodeTypeSTY, FRBAddressModeAbsolute },
    /* $8D */ { FRBOpcodeTypeSTA, FRBAddressModeAbsolute },
    /* $8E */ { FRBOpcodeTypeSTX, FRBAddressModeAbsolute },
    /* $8F */ { FRBOpcodeTypeBBS0, FRBAddressModeZeroPageProgramCounterRelative },

    /* $90 */ { FRBOpcodeTypeBCC, FRBAddressModeProgramCounterRelative },
    /* $91 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirectIndexedY },
    /* $92 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndirect },
    /* $93 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $94 */ { FRBOpcodeTypeSTY, FRBAddressModeZeroPageIndexedX },
    /* $95 */ { FRBOpcodeTypeSTA, FRBAddressModeZeroPageIndexedX },
    /* $96 */ { FRBOpcodeTypeSTX, FRBAddressModeZeroPageIndexedY },
    /* $97 */ { FRBOpcodeTypeSMB1, FRBAddressModeZeroPage },
    /* $98 */ { FRBOpcodeTypeTYA, FRBAddressModeImplied },
    /* $99 */ { FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedY },
    /* $9A */ { FRBOpcodeTypeTXS, FRBAddressModeImplied },
    /* $9B */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $9C */ { FRBOpcodeTypeSTZ, FRBAddressModeAbsolute },
    /* $9D */ { FRBOpcodeTypeSTA, FRBAddressModeAbsoluteIndexedX },
    /* $9E */ { FRBOpcodeTypeSTZ, FRBAddressModeAbsoluteIndexedX },
    /* $9F */ { FRBOpcodeTypeBBS1, FRBAddressModeZeroPageProgramCounterRelative },

    /* $A0 */ { FRBOpcodeTypeLDY, FRBAddressModeImmediate },
    /* $A1 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedIndirect },
    /* $A2 */ { FRBOpcodeTypeLDX, FRBAddressModeImmediate },
    /* $A3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $A4 */ { FRBOpcodeTypeLDY, FRBAddressModeZeroPage },
    /* $A5 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPage },
    /* $A6 */ { FRBOpcodeTypeLDX, FRBAddressModeZeroPage },
    /* $A7 */ { FRBOpcodeTypeSMB2, FRBAddressModeZeroPage },
    /* $A8 */ { FRBOpcodeTypeTAY, FRBAddressModeImplied },
    /* $A9 */ { FRBOpcodeTypeLDA, FRBAddressModeImmediate },
    /* $AA */ { FRBOpcodeTypeTAX, FRBAddressModeImplied },
    /* $AB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $AC */ { FRBOpcodeTypeLDY, FRBAddressModeAbsolute },
    /* $AD */ { FRBOpcodeTypeLDA, FRBAddressModeAbsolute },
    /* $AE */ { FRBOpcodeTypeLDX, FRBAddressModeAbsolute },
    /* $AF */ { FRBOpcodeTypeBBS2, FRBAddressModeZeroPageProgramCounterRelative },

    /* $B0 */ { FRBOpcodeTypeBCS, FRBAddressModeProgramCounterRelative },
    /* $B1 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndirectIndexedY },
    /* $B2 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndirect },
    /* $B3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $B4 */ { FRBOpcodeTypeLDY, FRBAddressModeZeroPageIndexedX },
    /* $B5 */ { FRBOpcodeTypeLDA, FRBAddressModeZeroPageIndexedX },
    /* $B6 */ { FRBOpcodeTypeLDX, FRBAddressModeZeroPageIndexedY },
    /* $B7 */ { FRBOpcodeTypeSMB3, FRBAddressModeZeroPage },
    /* $B8 */ { FRBOpcodeTypeCLV, FRBAddressModeImplied },
    /* $B9 */ { FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedY },
    /* $BA */ { FRBOpcodeTypeTSX, FRBAddressModeImplied },
    /* $BB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $BC */ { FRBOpcodeTypeLDY, FRBAddressModeAbsoluteIndexedX },
    /* $BD */ { FRBOpcodeTypeLDA, FRBAddressModeAbsoluteIndexedX },
    /* $BE */ { FRBOpcodeTypeLDX, FRBAddressModeAbsoluteIndexedY },
    /* $BF */ { FRBOpcodeTypeBBS3, FRBAddressModeZeroPageProgramCounterRelative },

    /* $C0 */ { FRBOpcodeTypeCPY, FRBAddressModeImmediate },
    /* $C1 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndexedIndirect },
    /* $C2 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $C3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $C4 */ { FRBOpcodeTypeCPY, FRBAddressModeZeroPage },
    /* $C5 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPage },
    /* $C6 */ { FRBOpcodeTypeDEC, FRBAddressModeZeroPage },
    /* $C7 */ { FRBOpcodeTypeSMB4, FRBAddressModeZeroPage },
    /* $C8 */ { FRBOpcodeTypeINY, FRBAddressModeImplied },
    /* $C9 */ { FRBOpcodeTypeCMP, FRBAddressModeImmediate },
    /* $CA */ { FRBOpcodeTypeDEX, FRBAddressModeImplied },
    /* $CB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $CC */ { FRBOpcodeTypeCPY, FRBAddressModeAbsolute },
    /* $CD */ { FRBOpcodeTypeCMP, FRBAddressModeAbsolute },
    /* $CE */ { FRBOpcodeTypeDEC, FRBAddressModeAbsolute },
    /* $CF */ { FRBOpcodeTypeBBS4, FRBAddressModeZeroPageProgramCounterRelative },

    /* $D0 */ { FRBOpcodeTypeBNE, FRBAddressModeProgramCounterRelative },
    /* $D1 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirectIndexedY },
    /* $D2 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndirect },
    /* $D3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $D4 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $D5 */ { FRBOpcodeTypeCMP, FRBAddressModeZeroPageIndexedX },
    /* $D6 */ { FRBOpcodeTypeDEC, FRBAddressModeZeroPageIndexedX },
    /* $D7 */ { FRBOpcodeTypeSMB5, FRBAddressModeZeroPage },
    /* $D8 */ { FRBOpcodeTypeCLD, FRBAddressModeImplied },
    /* $D9 */ { FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedY },
    /* $DA */ { FRBOpcodeTypePHX, FRBAddressModeStack },
    /* $DB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $DC */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $DD */ { FRBOpcodeTypeCMP, FRBAddressModeAbsoluteIndexedX },
    /* $DE */ { FRBOpcodeTypeDEC, FRBAddressModeAbsoluteIndexedX },
    /* $DF */ { FRBOpcodeTypeBBS5, FRBAddressModeZeroPageProgramCounterRelative },

    /* $E0 */ { FRBOpcodeTypeCPX, FRBAddressModeImmediate },
    /* $E1 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndexedIndirect },
    /* $E2 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $E3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $E4 */ { FRBOpcodeTypeCPX, FRBAddressModeZeroPage },
    /* $E5 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPage },
    /* $E6 */ { FRBOpcodeTypeINC, FRBAddressModeZeroPage },
    /* $E7 */ { FRBOpcodeTypeSMB6, FRBAddressModeZeroPage },
    /* $E8 */ { FRBOpcodeTypeINX, FRBAddressModeImplied },
    /* $E9 */ { FRBOpcodeTypeSBC, FRBAddressModeImmediate },
    /* $EA */ { FRBOpcodeTypeNOP, FRBAddressModeImplied },
    /* $EB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $EC */ { FRBOpcodeTypeCPX, FRBAddressModeAbsolute },
    /* $ED */ { FRBOpcodeTypeSBC, FRBAddressModeAbsolute },
    /* $EE */ { FRBOpcodeTypeINC, FRBAddressModeAbsolute },
    /* $EF */ { FRBOpcodeTypeBBS6, FRBAddressModeZeroPageProgramCounterRelative },

    /* $F0 */ { FRBOpcodeTypeBEQ, FRBAddressModeProgramCounterRelative },
    /* $F1 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirectIndexedY },
    /* $F2 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndirect },
    /* $F3 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $F4 */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $F5 */ { FRBOpcodeTypeSBC, FRBAddressModeZeroPageIndexedX },
    /* $F6 */ { FRBOpcodeTypeINC, FRBAddressModeZeroPageIndexedX },
    /* $F7 */ { FRBOpcodeTypeSMB7, FRBAddressModeZeroPage },
    /* $F8 */ { FRBOpcodeTypeSED, FRBAddressModeImplied },
    /* $F9 */ { FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedY },
    /* $FA */ { FRBOpcodeTypePLX, FRBAddressModeStack },
    /* $FB */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $FC */ { FRBOpcodeTypeUndocumented, FRBAddressModeUnknown },
    /* $FD */ { FRBOpcodeTypeSBC, FRBAddressModeAbsoluteIndexedX },
    /* $FE */ { FRBOpcodeTypeINC, FRBAddressModeAbsoluteIndexedX },
    /* $FF */ { FRBOpcodeTypeBBS7, FRBAddressModeZeroPageProgramCounterRelative },
};

#endif