/*!
 Copyright (c) 2014, Alessandro Gatti
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef MOS6502CPU_MOS6502Opcodes_h
#define MOS6502CPU_MOS6502Opcodes_h

typedef NS_ENUM(NSUInteger, MOS6502AddressMode) {
    MOS6502AddressModeAbsolute = 0,
    MOS6502AddressModeAbsoluteXIndexed,
    MOS6502AddressModeAbsoluteYIndexed,
    MOS6502AddressModeImmediate,
    MOS6502AddressModeImplied,
    MOS6502AddressModeIndirect,
    MOS6502AddressModeIndirectXIndexed,
    MOS6502AddressModeIndirectYIndexed,
    MOS6502AddressModeRelative,
    MOS6502AddressModeZeropage,
    MOS6502AddressModeZeropageXIndexed,
    MOS6502AddressModeZeropageYIndexed,
    MOS6502AddressModeUnknown
};

typedef NS_ENUM(NSUInteger, MOS6502OpcodeType) {
    MOS6502OpcodeTypeSystem = 0,
    MOS6502OpcodeTypeLoad,
    MOS6502OpcodeTypeStore,
    MOS6502OpcodeTypeRegisterTransfers,
    MOS6502OpcodeTypeStack,
    MOS6502OpcodeTypeLogical,
    MOS6502OpcodeTypeComparison,
    MOS6502OpcodeTypeArithmetic,
    MOS6502OpcodeTypeIncrementDecrement,
    MOS6502OpcodeTypeShifts,
    MOS6502OpcodeTypeJumps,
    MOS6502OpcodeTypeBranches,
    MOS6502OpcodeTypeStatusFlagChanges,
    MOS6502OpcodeTypeUnknown
};

struct MOS6502Opcode {
    MOS6502AddressMode addressMode;
    const char *name;
    DisasmBranchType branchType;
    MOS6502OpcodeType opcodeType;
};

static struct MOS6502Opcode kOpcodes[256] = {
    { MOS6502AddressModeImplied, "BRK", DISASM_BRANCH_NONE, MOS6502OpcodeTypeSystem },
    { MOS6502AddressModeIndirectXIndexed, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeZeropage, "ASL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "PHP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStack },
    { MOS6502AddressModeImmediate, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeImplied, "ASL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeAbsolute, "ASL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BPL", DISASM_BRANCH_JNS, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeZeropageXIndexed, "ASL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "CLC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStatusFlagChanges },
    { MOS6502AddressModeAbsoluteYIndexed, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "ORA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeAbsoluteXIndexed, "ASL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "JSR", DISASM_BRANCH_CALL, MOS6502OpcodeTypeJumps },
    { MOS6502AddressModeIndirectXIndexed, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "BIT", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeZeropage, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeZeropage, "ROL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "PLP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStack },
    { MOS6502AddressModeImmediate, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeImplied, "ROL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "BIT", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeAbsolute, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeAbsolute, "ROL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BMI", DISASM_BRANCH_JS, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeZeropageXIndexed, "ROL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "SEC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStatusFlagChanges },
    { MOS6502AddressModeAbsoluteYIndexed, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "AND", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeAbsoluteXIndexed, "ROL", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "RTI", DISASM_BRANCH_RET, MOS6502OpcodeTypeSystem },
    { MOS6502AddressModeIndirectXIndexed, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeZeropage, "LSR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "PHA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStack },
    { MOS6502AddressModeImmediate, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeImplied, "LSR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "JMP", DISASM_BRANCH_JMP, MOS6502OpcodeTypeJumps },
    { MOS6502AddressModeAbsolute, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeAbsolute, "LSR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BVC", DISASM_BRANCH_JNO, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeZeropageXIndexed, "LSR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "CLI", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStatusFlagChanges },
    { MOS6502AddressModeAbsoluteYIndexed, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "EOR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLogical },
    { MOS6502AddressModeAbsoluteXIndexed, "LSR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "RTS", DISASM_BRANCH_RET, MOS6502OpcodeTypeSystem },
    { MOS6502AddressModeIndirectXIndexed, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeZeropage, "ROR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "PLA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStack },
    { MOS6502AddressModeImmediate, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeImplied, "ROR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeIndirect, "JMP", DISASM_BRANCH_JMP, MOS6502OpcodeTypeJumps },
    { MOS6502AddressModeAbsolute, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeAbsolute, "ROR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BVS", DISASM_BRANCH_JO, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeZeropageXIndexed, "ROR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "SEI", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStatusFlagChanges },
    { MOS6502AddressModeAbsoluteYIndexed, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "ADC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeAbsoluteXIndexed, "ROR", DISASM_BRANCH_NONE, MOS6502OpcodeTypeShifts },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeIndirectXIndexed, "STA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "STY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeZeropage, "STA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeZeropage, "STX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "DEY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "TXA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeRegisterTransfers },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "STY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeAbsolute, "STA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeAbsolute, "STX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BCC", DISASM_BRANCH_JNC, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "STA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "STY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeZeropageXIndexed, "STA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeZeropageYIndexed, "STX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "TYA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeRegisterTransfers },
    { MOS6502AddressModeAbsoluteYIndexed, "STA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeImplied, "TXS", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStack },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "STA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStore },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImmediate, "LDY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeIndirectXIndexed, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeImmediate, "LDX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "LDY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeZeropage, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeZeropage, "LDX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "TAY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeRegisterTransfers },
    { MOS6502AddressModeImmediate, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeImplied, "TAX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeRegisterTransfers },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "LDY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeAbsolute, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeAbsolute, "LDX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BCS", DISASM_BRANCH_JC, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "LDY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeZeropageXIndexed, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeZeropageYIndexed, "LDX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "CLV", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStatusFlagChanges },
    { MOS6502AddressModeAbsoluteYIndexed, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeImplied, "TSX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStack },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "LDY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeAbsoluteXIndexed, "LDA", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeAbsoluteYIndexed, "LDX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeLoad },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImmediate, "CPY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeIndirectXIndexed, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "CPY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeZeropage, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeZeropage, "DEC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "INY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeImmediate, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeImplied, "DEX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "CPY", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeAbsolute, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeAbsolute, "DEC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BNE", DISASM_BRANCH_JNE, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeZeropageXIndexed, "DEC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "CLD", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStatusFlagChanges },
    { MOS6502AddressModeAbsoluteYIndexed, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "CMP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeAbsoluteXIndexed, "DEC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImmediate, "CPX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeIndirectXIndexed, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropage, "CPX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeComparison },
    { MOS6502AddressModeZeropage, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeZeropage, "INC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "INX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeImmediate, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeImplied, "NOP", DISASM_BRANCH_NONE, MOS6502OpcodeTypeSystem },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsolute, "CPX", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeAbsolute, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeAbsolute, "INC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeRelative, "BEQ", DISASM_BRANCH_JE, MOS6502OpcodeTypeBranches },
    { MOS6502AddressModeIndirectYIndexed, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeZeropageXIndexed, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeZeropageXIndexed, "INC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeImplied, "SED", DISASM_BRANCH_NONE, MOS6502OpcodeTypeStatusFlagChanges },
    { MOS6502AddressModeAbsoluteYIndexed, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown },
    { MOS6502AddressModeAbsoluteXIndexed, "SBC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeArithmetic },
    { MOS6502AddressModeAbsoluteXIndexed, "INC", DISASM_BRANCH_NONE, MOS6502OpcodeTypeIncrementDecrement },
    { MOS6502AddressModeUnknown, nil, DISASM_BRANCH_NONE, MOS6502OpcodeTypeUnknown }
};

#endif
