/*
 Copyright (c) 2014-2017, Alessandro Gatti - frob.it
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#import "FRBTMS1000.h"

static const FRBInstruction kOpcodes[256];

@implementation FRBTMS1000

+ (NSString *_Nonnull)family {
  return @"Texas Instruments";
}

+ (NSString *_Nonnull)model {
  return @"TMS1000";
}

+ (BOOL)exported {
  return YES;
}

+ (int)addressSpaceWidth {
  return 16;
}

- (FRBInstruction)instructionForByte:(uint8_t)byte {
  return kOpcodes[byte];
}

@end

static const FRBInstruction kOpcodes[256] = {
    {FRBOpcodeTypeCOMX, FRBInstructionEncodingIV},
    {FRBOpcodeTypeA8AAC, FRBInstructionEncodingIV},
    {FRBOpcodeTypeYNEA, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTAM, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTAMZA, FRBInstructionEncodingIV},
    {FRBOpcodeTypeA10AAC, FRBInstructionEncodingIV},
    {FRBOpcodeTypeA6AAC, FRBInstructionEncodingIV},
    {FRBOpcodeTypeDAN, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTKA, FRBInstructionEncodingIV},
    {FRBOpcodeTypeKNEZ, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTDO, FRBInstructionEncodingIV},
    {FRBOpcodeTypeCLO, FRBInstructionEncodingIV},
    {FRBOpcodeTypeRSTR, FRBInstructionEncodingIV},
    {FRBOpcodeTypeSETR, FRBInstructionEncodingIV},
    {FRBOpcodeTypeIA, FRBInstructionEncodingIV},
    {FRBOpcodeTypeRETN, FRBInstructionEncodingIV},

    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},
    {FRBOpcodeTypeLDP, FRBInstructionEncodingII},

    {FRBOpcodeTypeTAMIY, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTMA, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTMY, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTYA, FRBInstructionEncodingIV},
    {FRBOpcodeTypeTAY, FRBInstructionEncodingIV},
    {FRBOpcodeTypeAMAAC, FRBInstructionEncodingIV},
    {FRBOpcodeTypeMNEZ, FRBInstructionEncodingIV},
    {FRBOpcodeTypeSAMAN, FRBInstructionEncodingIV},
    {FRBOpcodeTypeIMAC, FRBInstructionEncodingIV},
    {FRBOpcodeTypeALEM, FRBInstructionEncodingIV},
    {FRBOpcodeTypeDMAN, FRBInstructionEncodingIV},
    {FRBOpcodeTypeIYC, FRBInstructionEncodingIV},
    {FRBOpcodeTypeDYN, FRBInstructionEncodingIV},
    {FRBOpcodeTypeCPAIZ, FRBInstructionEncodingIV},
    {FRBOpcodeTypeXMA, FRBInstructionEncodingIV},
    {FRBOpcodeTypeCLA, FRBInstructionEncodingIV},

    {FRBOpcodeTypeSBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeSBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeSBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeSBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeRBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeRBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeRBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeRBIT, FRBInstructionEncodingIII},
    {FRBOpcodeTypeTBIT1, FRBInstructionEncodingIII},
    {FRBOpcodeTypeTBIT1, FRBInstructionEncodingIII},
    {FRBOpcodeTypeTBIT1, FRBInstructionEncodingIII},
    {FRBOpcodeTypeTBIT1, FRBInstructionEncodingIII},
    {FRBOpcodeTypeLDX, FRBInstructionEncodingIII},
    {FRBOpcodeTypeLDX, FRBInstructionEncodingIII},
    {FRBOpcodeTypeLDX, FRBInstructionEncodingIII},
    {FRBOpcodeTypeLDX, FRBInstructionEncodingIII},

    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCY, FRBInstructionEncodingII},

    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeYNEC, FRBInstructionEncodingII},

    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},
    {FRBOpcodeTypeTCMIY, FRBInstructionEncodingII},

    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},
    {FRBOpcodeTypeALEC, FRBInstructionEncodingII},

    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeBR, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI},
    {FRBOpcodeTypeCALL, FRBInstructionEncodingI}};
